// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: media_set/media_set_service.proto

package media_set

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	MediaSetService_CreateMediaSet_FullMethodName               = "/open_foundry.media_set.MediaSetService/CreateMediaSet"
	MediaSetService_GetMediaSet_FullMethodName                  = "/open_foundry.media_set.MediaSetService/GetMediaSet"
	MediaSetService_ListMediaSets_FullMethodName                = "/open_foundry.media_set.MediaSetService/ListMediaSets"
	MediaSetService_DeleteMediaSet_FullMethodName               = "/open_foundry.media_set.MediaSetService/DeleteMediaSet"
	MediaSetService_OpenTransaction_FullMethodName              = "/open_foundry.media_set.MediaSetService/OpenTransaction"
	MediaSetService_CommitTransaction_FullMethodName            = "/open_foundry.media_set.MediaSetService/CommitTransaction"
	MediaSetService_AbortTransaction_FullMethodName             = "/open_foundry.media_set.MediaSetService/AbortTransaction"
	MediaSetService_ListMediaItems_FullMethodName               = "/open_foundry.media_set.MediaSetService/ListMediaItems"
	MediaSetService_GetMediaItem_FullMethodName                 = "/open_foundry.media_set.MediaSetService/GetMediaItem"
	MediaSetService_DeleteMediaItem_FullMethodName              = "/open_foundry.media_set.MediaSetService/DeleteMediaItem"
	MediaSetService_GeneratePresignedUploadUrl_FullMethodName   = "/open_foundry.media_set.MediaSetService/GeneratePresignedUploadUrl"
	MediaSetService_GeneratePresignedDownloadUrl_FullMethodName = "/open_foundry.media_set.MediaSetService/GeneratePresignedDownloadUrl"
	MediaSetService_RegisterVirtualMediaItem_FullMethodName     = "/open_foundry.media_set.MediaSetService/RegisterVirtualMediaItem"
)

type MediaSetServiceClient interface {
	CreateMediaSet(ctx context.Context, in *CreateMediaSetRequest, opts ...grpc.CallOption) (*MediaSet, error)
	GetMediaSet(ctx context.Context, in *GetMediaSetRequest, opts ...grpc.CallOption) (*MediaSet, error)
	ListMediaSets(ctx context.Context, in *ListMediaSetsRequest, opts ...grpc.CallOption) (*ListMediaSetsResponse, error)
	DeleteMediaSet(ctx context.Context, in *DeleteMediaSetRequest, opts ...grpc.CallOption) (*DeleteMediaSetResponse, error)
	OpenTransaction(ctx context.Context, in *OpenTransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
	CommitTransaction(ctx context.Context, in *CommitTransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
	AbortTransaction(ctx context.Context, in *AbortTransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
	ListMediaItems(ctx context.Context, in *ListMediaItemsRequest, opts ...grpc.CallOption) (*ListMediaItemsResponse, error)
	GetMediaItem(ctx context.Context, in *GetMediaItemRequest, opts ...grpc.CallOption) (*MediaItem, error)
	DeleteMediaItem(ctx context.Context, in *DeleteMediaItemRequest, opts ...grpc.CallOption) (*DeleteMediaItemResponse, error)
	GeneratePresignedUploadUrl(ctx context.Context, in *GeneratePresignedUploadUrlRequest, opts ...grpc.CallOption) (*PresignedUrlResponse, error)
	GeneratePresignedDownloadUrl(ctx context.Context, in *GeneratePresignedDownloadUrlRequest, opts ...grpc.CallOption) (*PresignedUrlResponse, error)
	RegisterVirtualMediaItem(ctx context.Context, in *RegisterVirtualMediaItemRequest, opts ...grpc.CallOption) (*MediaItem, error)
}

type mediaSetServiceClient struct{ cc grpc.ClientConnInterface }

func NewMediaSetServiceClient(cc grpc.ClientConnInterface) MediaSetServiceClient {
	return &mediaSetServiceClient{cc}
}

func (c *mediaSetServiceClient) CreateMediaSet(ctx context.Context, in *CreateMediaSetRequest, opts ...grpc.CallOption) (*MediaSet, error) {
	out := new(MediaSet)
	err := c.cc.Invoke(ctx, MediaSetService_CreateMediaSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (c *mediaSetServiceClient) GetMediaSet(ctx context.Context, in *GetMediaSetRequest, opts ...grpc.CallOption) (*MediaSet, error) {
	out := new(MediaSet)
	err := c.cc.Invoke(ctx, MediaSetService_GetMediaSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (c *mediaSetServiceClient) ListMediaSets(ctx context.Context, in *ListMediaSetsRequest, opts ...grpc.CallOption) (*ListMediaSetsResponse, error) {
	out := new(ListMediaSetsResponse)
	err := c.cc.Invoke(ctx, MediaSetService_ListMediaSets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (c *mediaSetServiceClient) DeleteMediaSet(ctx context.Context, in *DeleteMediaSetRequest, opts ...grpc.CallOption) (*DeleteMediaSetResponse, error) {
	out := new(DeleteMediaSetResponse)
	err := c.cc.Invoke(ctx, MediaSetService_DeleteMediaSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (c *mediaSetServiceClient) OpenTransaction(ctx context.Context, in *OpenTransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, MediaSetService_OpenTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (c *mediaSetServiceClient) CommitTransaction(ctx context.Context, in *CommitTransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, MediaSetService_CommitTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (c *mediaSetServiceClient) AbortTransaction(ctx context.Context, in *AbortTransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, MediaSetService_AbortTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (c *mediaSetServiceClient) ListMediaItems(ctx context.Context, in *ListMediaItemsRequest, opts ...grpc.CallOption) (*ListMediaItemsResponse, error) {
	out := new(ListMediaItemsResponse)
	err := c.cc.Invoke(ctx, MediaSetService_ListMediaItems_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (c *mediaSetServiceClient) GetMediaItem(ctx context.Context, in *GetMediaItemRequest, opts ...grpc.CallOption) (*MediaItem, error) {
	out := new(MediaItem)
	err := c.cc.Invoke(ctx, MediaSetService_GetMediaItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (c *mediaSetServiceClient) DeleteMediaItem(ctx context.Context, in *DeleteMediaItemRequest, opts ...grpc.CallOption) (*DeleteMediaItemResponse, error) {
	out := new(DeleteMediaItemResponse)
	err := c.cc.Invoke(ctx, MediaSetService_DeleteMediaItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (c *mediaSetServiceClient) GeneratePresignedUploadUrl(ctx context.Context, in *GeneratePresignedUploadUrlRequest, opts ...grpc.CallOption) (*PresignedUrlResponse, error) {
	out := new(PresignedUrlResponse)
	err := c.cc.Invoke(ctx, MediaSetService_GeneratePresignedUploadUrl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (c *mediaSetServiceClient) GeneratePresignedDownloadUrl(ctx context.Context, in *GeneratePresignedDownloadUrlRequest, opts ...grpc.CallOption) (*PresignedUrlResponse, error) {
	out := new(PresignedUrlResponse)
	err := c.cc.Invoke(ctx, MediaSetService_GeneratePresignedDownloadUrl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (c *mediaSetServiceClient) RegisterVirtualMediaItem(ctx context.Context, in *RegisterVirtualMediaItemRequest, opts ...grpc.CallOption) (*MediaItem, error) {
	out := new(MediaItem)
	err := c.cc.Invoke(ctx, MediaSetService_RegisterVirtualMediaItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type MediaSetServiceServer interface {
	CreateMediaSet(context.Context, *CreateMediaSetRequest) (*MediaSet, error)
	GetMediaSet(context.Context, *GetMediaSetRequest) (*MediaSet, error)
	ListMediaSets(context.Context, *ListMediaSetsRequest) (*ListMediaSetsResponse, error)
	DeleteMediaSet(context.Context, *DeleteMediaSetRequest) (*DeleteMediaSetResponse, error)
	OpenTransaction(context.Context, *OpenTransactionRequest) (*Transaction, error)
	CommitTransaction(context.Context, *CommitTransactionRequest) (*Transaction, error)
	AbortTransaction(context.Context, *AbortTransactionRequest) (*Transaction, error)
	ListMediaItems(context.Context, *ListMediaItemsRequest) (*ListMediaItemsResponse, error)
	GetMediaItem(context.Context, *GetMediaItemRequest) (*MediaItem, error)
	DeleteMediaItem(context.Context, *DeleteMediaItemRequest) (*DeleteMediaItemResponse, error)
	GeneratePresignedUploadUrl(context.Context, *GeneratePresignedUploadUrlRequest) (*PresignedUrlResponse, error)
	GeneratePresignedDownloadUrl(context.Context, *GeneratePresignedDownloadUrlRequest) (*PresignedUrlResponse, error)
	RegisterVirtualMediaItem(context.Context, *RegisterVirtualMediaItemRequest) (*MediaItem, error)
}

type UnimplementedMediaSetServiceServer struct{}

func (UnimplementedMediaSetServiceServer) CreateMediaSet(context.Context, *CreateMediaSetRequest) (*MediaSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMediaSet not implemented")
}
func (UnimplementedMediaSetServiceServer) GetMediaSet(context.Context, *GetMediaSetRequest) (*MediaSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMediaSet not implemented")
}
func (UnimplementedMediaSetServiceServer) ListMediaSets(context.Context, *ListMediaSetsRequest) (*ListMediaSetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMediaSets not implemented")
}
func (UnimplementedMediaSetServiceServer) DeleteMediaSet(context.Context, *DeleteMediaSetRequest) (*DeleteMediaSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMediaSet not implemented")
}
func (UnimplementedMediaSetServiceServer) OpenTransaction(context.Context, *OpenTransactionRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenTransaction not implemented")
}
func (UnimplementedMediaSetServiceServer) CommitTransaction(context.Context, *CommitTransactionRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitTransaction not implemented")
}
func (UnimplementedMediaSetServiceServer) AbortTransaction(context.Context, *AbortTransactionRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortTransaction not implemented")
}
func (UnimplementedMediaSetServiceServer) ListMediaItems(context.Context, *ListMediaItemsRequest) (*ListMediaItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMediaItems not implemented")
}
func (UnimplementedMediaSetServiceServer) GetMediaItem(context.Context, *GetMediaItemRequest) (*MediaItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMediaItem not implemented")
}
func (UnimplementedMediaSetServiceServer) DeleteMediaItem(context.Context, *DeleteMediaItemRequest) (*DeleteMediaItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMediaItem not implemented")
}
func (UnimplementedMediaSetServiceServer) GeneratePresignedUploadUrl(context.Context, *GeneratePresignedUploadUrlRequest) (*PresignedUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePresignedUploadUrl not implemented")
}
func (UnimplementedMediaSetServiceServer) GeneratePresignedDownloadUrl(context.Context, *GeneratePresignedDownloadUrlRequest) (*PresignedUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePresignedDownloadUrl not implemented")
}
func (UnimplementedMediaSetServiceServer) RegisterVirtualMediaItem(context.Context, *RegisterVirtualMediaItemRequest) (*MediaItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterVirtualMediaItem not implemented")
}

func RegisterMediaSetServiceServer(s grpc.ServiceRegistrar, srv MediaSetServiceServer) {
	s.RegisterService(&MediaSetService_ServiceDesc, srv)
}

type methodHandler[Req any, Resp any] func(context.Context, *Req) (*Resp, error)

func unaryHandler[Req any, Resp any](srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor, info *grpc.UnaryServerInfo, fn func(MediaSetServiceServer, context.Context, *Req) (*Resp, error)) (any, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return fn(srv.(MediaSetServiceServer), ctx, in)
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return fn(srv.(MediaSetServiceServer), ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaSetService_CreateMediaSet_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	return unaryHandler(srv, ctx, dec, interceptor, &grpc.UnaryServerInfo{Server: srv, FullMethod: MediaSetService_CreateMediaSet_FullMethodName}, func(s MediaSetServiceServer, c context.Context, r *CreateMediaSetRequest) (*MediaSet, error) {
		return s.CreateMediaSet(c, r)
	})
}
func _MediaSetService_GetMediaSet_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	return unaryHandler(srv, ctx, dec, interceptor, &grpc.UnaryServerInfo{Server: srv, FullMethod: MediaSetService_GetMediaSet_FullMethodName}, func(s MediaSetServiceServer, c context.Context, r *GetMediaSetRequest) (*MediaSet, error) {
		return s.GetMediaSet(c, r)
	})
}
func _MediaSetService_ListMediaSets_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	return unaryHandler(srv, ctx, dec, interceptor, &grpc.UnaryServerInfo{Server: srv, FullMethod: MediaSetService_ListMediaSets_FullMethodName}, func(s MediaSetServiceServer, c context.Context, r *ListMediaSetsRequest) (*ListMediaSetsResponse, error) {
		return s.ListMediaSets(c, r)
	})
}
func _MediaSetService_DeleteMediaSet_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	return unaryHandler(srv, ctx, dec, interceptor, &grpc.UnaryServerInfo{Server: srv, FullMethod: MediaSetService_DeleteMediaSet_FullMethodName}, func(s MediaSetServiceServer, c context.Context, r *DeleteMediaSetRequest) (*DeleteMediaSetResponse, error) {
		return s.DeleteMediaSet(c, r)
	})
}
func _MediaSetService_OpenTransaction_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	return unaryHandler(srv, ctx, dec, interceptor, &grpc.UnaryServerInfo{Server: srv, FullMethod: MediaSetService_OpenTransaction_FullMethodName}, func(s MediaSetServiceServer, c context.Context, r *OpenTransactionRequest) (*Transaction, error) {
		return s.OpenTransaction(c, r)
	})
}
func _MediaSetService_CommitTransaction_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	return unaryHandler(srv, ctx, dec, interceptor, &grpc.UnaryServerInfo{Server: srv, FullMethod: MediaSetService_CommitTransaction_FullMethodName}, func(s MediaSetServiceServer, c context.Context, r *CommitTransactionRequest) (*Transaction, error) {
		return s.CommitTransaction(c, r)
	})
}
func _MediaSetService_AbortTransaction_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	return unaryHandler(srv, ctx, dec, interceptor, &grpc.UnaryServerInfo{Server: srv, FullMethod: MediaSetService_AbortTransaction_FullMethodName}, func(s MediaSetServiceServer, c context.Context, r *AbortTransactionRequest) (*Transaction, error) {
		return s.AbortTransaction(c, r)
	})
}
func _MediaSetService_ListMediaItems_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	return unaryHandler(srv, ctx, dec, interceptor, &grpc.UnaryServerInfo{Server: srv, FullMethod: MediaSetService_ListMediaItems_FullMethodName}, func(s MediaSetServiceServer, c context.Context, r *ListMediaItemsRequest) (*ListMediaItemsResponse, error) {
		return s.ListMediaItems(c, r)
	})
}
func _MediaSetService_GetMediaItem_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	return unaryHandler(srv, ctx, dec, interceptor, &grpc.UnaryServerInfo{Server: srv, FullMethod: MediaSetService_GetMediaItem_FullMethodName}, func(s MediaSetServiceServer, c context.Context, r *GetMediaItemRequest) (*MediaItem, error) {
		return s.GetMediaItem(c, r)
	})
}
func _MediaSetService_DeleteMediaItem_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	return unaryHandler(srv, ctx, dec, interceptor, &grpc.UnaryServerInfo{Server: srv, FullMethod: MediaSetService_DeleteMediaItem_FullMethodName}, func(s MediaSetServiceServer, c context.Context, r *DeleteMediaItemRequest) (*DeleteMediaItemResponse, error) {
		return s.DeleteMediaItem(c, r)
	})
}
func _MediaSetService_GeneratePresignedUploadUrl_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	return unaryHandler(srv, ctx, dec, interceptor, &grpc.UnaryServerInfo{Server: srv, FullMethod: MediaSetService_GeneratePresignedUploadUrl_FullMethodName}, func(s MediaSetServiceServer, c context.Context, r *GeneratePresignedUploadUrlRequest) (*PresignedUrlResponse, error) {
		return s.GeneratePresignedUploadUrl(c, r)
	})
}
func _MediaSetService_GeneratePresignedDownloadUrl_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	return unaryHandler(srv, ctx, dec, interceptor, &grpc.UnaryServerInfo{Server: srv, FullMethod: MediaSetService_GeneratePresignedDownloadUrl_FullMethodName}, func(s MediaSetServiceServer, c context.Context, r *GeneratePresignedDownloadUrlRequest) (*PresignedUrlResponse, error) {
		return s.GeneratePresignedDownloadUrl(c, r)
	})
}
func _MediaSetService_RegisterVirtualMediaItem_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	return unaryHandler(srv, ctx, dec, interceptor, &grpc.UnaryServerInfo{Server: srv, FullMethod: MediaSetService_RegisterVirtualMediaItem_FullMethodName}, func(s MediaSetServiceServer, c context.Context, r *RegisterVirtualMediaItemRequest) (*MediaItem, error) {
		return s.RegisterVirtualMediaItem(c, r)
	})
}

var MediaSetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "open_foundry.media_set.MediaSetService",
	HandlerType: (*MediaSetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "CreateMediaSet", Handler: _MediaSetService_CreateMediaSet_Handler},
		{MethodName: "GetMediaSet", Handler: _MediaSetService_GetMediaSet_Handler},
		{MethodName: "ListMediaSets", Handler: _MediaSetService_ListMediaSets_Handler},
		{MethodName: "DeleteMediaSet", Handler: _MediaSetService_DeleteMediaSet_Handler},
		{MethodName: "OpenTransaction", Handler: _MediaSetService_OpenTransaction_Handler},
		{MethodName: "CommitTransaction", Handler: _MediaSetService_CommitTransaction_Handler},
		{MethodName: "AbortTransaction", Handler: _MediaSetService_AbortTransaction_Handler},
		{MethodName: "ListMediaItems", Handler: _MediaSetService_ListMediaItems_Handler},
		{MethodName: "GetMediaItem", Handler: _MediaSetService_GetMediaItem_Handler},
		{MethodName: "DeleteMediaItem", Handler: _MediaSetService_DeleteMediaItem_Handler},
		{MethodName: "GeneratePresignedUploadUrl", Handler: _MediaSetService_GeneratePresignedUploadUrl_Handler},
		{MethodName: "GeneratePresignedDownloadUrl", Handler: _MediaSetService_GeneratePresignedDownloadUrl_Handler},
		{MethodName: "RegisterVirtualMediaItem", Handler: _MediaSetService_RegisterVirtualMediaItem_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "media_set/media_set_service.proto",
}
