// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: media_set/media_set.proto

package media_set

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Media schema accepted by a media set. Mirrors the Foundry-documented
// "permitted file formats" taxonomy (image, audio, video, document,
// spreadsheet, email).
type MediaSetSchema int32

const (
	MediaSetSchema_MEDIA_SET_SCHEMA_UNSPECIFIED MediaSetSchema = 0
	MediaSetSchema_MEDIA_SET_SCHEMA_IMAGE       MediaSetSchema = 1
	MediaSetSchema_MEDIA_SET_SCHEMA_AUDIO       MediaSetSchema = 2
	MediaSetSchema_MEDIA_SET_SCHEMA_VIDEO       MediaSetSchema = 3
	MediaSetSchema_MEDIA_SET_SCHEMA_DOCUMENT    MediaSetSchema = 4
	MediaSetSchema_MEDIA_SET_SCHEMA_SPREADSHEET MediaSetSchema = 5
	MediaSetSchema_MEDIA_SET_SCHEMA_EMAIL       MediaSetSchema = 6
)

// Enum value maps for MediaSetSchema.
var (
	MediaSetSchema_name = map[int32]string{
		0: "MEDIA_SET_SCHEMA_UNSPECIFIED",
		1: "MEDIA_SET_SCHEMA_IMAGE",
		2: "MEDIA_SET_SCHEMA_AUDIO",
		3: "MEDIA_SET_SCHEMA_VIDEO",
		4: "MEDIA_SET_SCHEMA_DOCUMENT",
		5: "MEDIA_SET_SCHEMA_SPREADSHEET",
		6: "MEDIA_SET_SCHEMA_EMAIL",
	}
	MediaSetSchema_value = map[string]int32{
		"MEDIA_SET_SCHEMA_UNSPECIFIED": 0,
		"MEDIA_SET_SCHEMA_IMAGE":       1,
		"MEDIA_SET_SCHEMA_AUDIO":       2,
		"MEDIA_SET_SCHEMA_VIDEO":       3,
		"MEDIA_SET_SCHEMA_DOCUMENT":    4,
		"MEDIA_SET_SCHEMA_SPREADSHEET": 5,
		"MEDIA_SET_SCHEMA_EMAIL":       6,
	}
)

func (x MediaSetSchema) Enum() *MediaSetSchema {
	p := new(MediaSetSchema)
	*p = x
	return p
}

func (x MediaSetSchema) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaSetSchema) Descriptor() protoreflect.EnumDescriptor {
	return file_media_set_media_set_proto_enumTypes[0].Descriptor()
}

func (MediaSetSchema) Type() protoreflect.EnumType {
	return &file_media_set_media_set_proto_enumTypes[0]
}

func (x MediaSetSchema) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaSetSchema.Descriptor instead.
func (MediaSetSchema) EnumDescriptor() ([]byte, []int) {
	return file_media_set_media_set_proto_rawDescGZIP(), []int{0}
}

// How writes are sealed on a media set.
//
// Foundry default is `TRANSACTIONLESS` — items are visible immediately and
// cannot be rolled back. `TRANSACTIONAL` mirrors dataset semantics: writes
// are staged in an open transaction and only visible after commit.
type TransactionPolicy int32

const (
	TransactionPolicy_TRANSACTION_POLICY_UNSPECIFIED     TransactionPolicy = 0
	TransactionPolicy_TRANSACTION_POLICY_TRANSACTIONLESS TransactionPolicy = 1
	TransactionPolicy_TRANSACTION_POLICY_TRANSACTIONAL   TransactionPolicy = 2
)

// Enum value maps for TransactionPolicy.
var (
	TransactionPolicy_name = map[int32]string{
		0: "TRANSACTION_POLICY_UNSPECIFIED",
		1: "TRANSACTION_POLICY_TRANSACTIONLESS",
		2: "TRANSACTION_POLICY_TRANSACTIONAL",
	}
	TransactionPolicy_value = map[string]int32{
		"TRANSACTION_POLICY_UNSPECIFIED":     0,
		"TRANSACTION_POLICY_TRANSACTIONLESS": 1,
		"TRANSACTION_POLICY_TRANSACTIONAL":   2,
	}
)

func (x TransactionPolicy) Enum() *TransactionPolicy {
	p := new(TransactionPolicy)
	*p = x
	return p
}

func (x TransactionPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_media_set_media_set_proto_enumTypes[1].Descriptor()
}

func (TransactionPolicy) Type() protoreflect.EnumType {
	return &file_media_set_media_set_proto_enumTypes[1]
}

func (x TransactionPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionPolicy.Descriptor instead.
func (TransactionPolicy) EnumDescriptor() ([]byte, []int) {
	return file_media_set_media_set_proto_rawDescGZIP(), []int{1}
}

// Lifecycle of a transactional write batch on a media set branch.
type TransactionState int32

const (
	TransactionState_TRANSACTION_STATE_UNSPECIFIED TransactionState = 0
	TransactionState_TRANSACTION_STATE_OPEN        TransactionState = 1
	TransactionState_TRANSACTION_STATE_COMMITTED   TransactionState = 2
	TransactionState_TRANSACTION_STATE_ABORTED     TransactionState = 3
)

// Enum value maps for TransactionState.
var (
	TransactionState_name = map[int32]string{
		0: "TRANSACTION_STATE_UNSPECIFIED",
		1: "TRANSACTION_STATE_OPEN",
		2: "TRANSACTION_STATE_COMMITTED",
		3: "TRANSACTION_STATE_ABORTED",
	}
	TransactionState_value = map[string]int32{
		"TRANSACTION_STATE_UNSPECIFIED": 0,
		"TRANSACTION_STATE_OPEN":        1,
		"TRANSACTION_STATE_COMMITTED":   2,
		"TRANSACTION_STATE_ABORTED":     3,
	}
)

func (x TransactionState) Enum() *TransactionState {
	p := new(TransactionState)
	*p = x
	return p
}

func (x TransactionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionState) Descriptor() protoreflect.EnumDescriptor {
	return file_media_set_media_set_proto_enumTypes[2].Descriptor()
}

func (TransactionState) Type() protoreflect.EnumType {
	return &file_media_set_media_set_proto_enumTypes[2]
}

func (x TransactionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionState.Descriptor instead.
func (TransactionState) EnumDescriptor() ([]byte, []int) {
	return file_media_set_media_set_proto_rawDescGZIP(), []int{2}
}

// A collection of media items (unstructured files) sharing a common schema.
//
// `rid` is a Foundry-style resource identifier
// (`ri.foundry.main.media_set.<uuid>`). When `virtual` is true the items
// are read directly from `source_rid` (an external system) rather than
// from OpenFoundry-managed object storage.
type MediaSet struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Rid        string                 `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProjectRid string                 `protobuf:"bytes,3,opt,name=project_rid,json=projectRid,proto3" json:"project_rid,omitempty"`
	Schema     MediaSetSchema         `protobuf:"varint,4,opt,name=schema,proto3,enum=open_foundry.media_set.MediaSetSchema" json:"schema,omitempty"`
	// Allowed MIME types. Empty = inferred from `schema`.
	AllowedMimeTypes  []string          `protobuf:"bytes,5,rep,name=allowed_mime_types,json=allowedMimeTypes,proto3" json:"allowed_mime_types,omitempty"`
	TransactionPolicy TransactionPolicy `protobuf:"varint,6,opt,name=transaction_policy,json=transactionPolicy,proto3,enum=open_foundry.media_set.TransactionPolicy" json:"transaction_policy,omitempty"`
	// Retention window in seconds. `0` means retain forever.
	RetentionSeconds int64 `protobuf:"varint,7,opt,name=retention_seconds,json=retentionSeconds,proto3" json:"retention_seconds,omitempty"`
	// True when the media set is virtual (data lives in `source_rid`).
	Virtual bool `protobuf:"varint,8,opt,name=virtual,proto3" json:"virtual,omitempty"`
	// External source RID for virtual media sets (data-connection source).
	SourceRid *string `protobuf:"bytes,9,opt,name=source_rid,json=sourceRid,proto3,oneof" json:"source_rid,omitempty"`
	// Marking RIDs (security classifications) attached to the media set.
	Markings      []string               `protobuf:"bytes,10,rep,name=markings,proto3" json:"markings,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,12,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaSet) Reset() {
	*x = MediaSet{}
	mi := &file_media_set_media_set_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSet) ProtoMessage() {}

func (x *MediaSet) ProtoReflect() protoreflect.Message {
	mi := &file_media_set_media_set_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaSet.ProtoReflect.Descriptor instead.
func (*MediaSet) Descriptor() ([]byte, []int) {
	return file_media_set_media_set_proto_rawDescGZIP(), []int{0}
}

func (x *MediaSet) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *MediaSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MediaSet) GetProjectRid() string {
	if x != nil {
		return x.ProjectRid
	}
	return ""
}

func (x *MediaSet) GetSchema() MediaSetSchema {
	if x != nil {
		return x.Schema
	}
	return MediaSetSchema_MEDIA_SET_SCHEMA_UNSPECIFIED
}

func (x *MediaSet) GetAllowedMimeTypes() []string {
	if x != nil {
		return x.AllowedMimeTypes
	}
	return nil
}

func (x *MediaSet) GetTransactionPolicy() TransactionPolicy {
	if x != nil {
		return x.TransactionPolicy
	}
	return TransactionPolicy_TRANSACTION_POLICY_UNSPECIFIED
}

func (x *MediaSet) GetRetentionSeconds() int64 {
	if x != nil {
		return x.RetentionSeconds
	}
	return 0
}

func (x *MediaSet) GetVirtual() bool {
	if x != nil {
		return x.Virtual
	}
	return false
}

func (x *MediaSet) GetSourceRid() string {
	if x != nil && x.SourceRid != nil {
		return *x.SourceRid
	}
	return ""
}

func (x *MediaSet) GetMarkings() []string {
	if x != nil {
		return x.Markings
	}
	return nil
}

func (x *MediaSet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MediaSet) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

// A single file inside a media set.
//
// `path` is the logical key (typically the original filename); uploads to
// the same path overwrite the previous item but keep prior versions
// reachable through the immutable `rid` (Foundry path-deduplication).
type MediaItem struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Rid         string                 `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	MediaSetRid string                 `protobuf:"bytes,2,opt,name=media_set_rid,json=mediaSetRid,proto3" json:"media_set_rid,omitempty"`
	Branch      string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	// RID of the transaction that wrote this item; empty for transactionless
	// media sets.
	TransactionRid string `protobuf:"bytes,4,opt,name=transaction_rid,json=transactionRid,proto3" json:"transaction_rid,omitempty"`
	Path           string `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	MimeType       string `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes      int64  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256         string `protobuf:"bytes,8,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Free-form metadata blob (JSON-encoded).
	Metadata  string                 `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// RID of the prior item this one replaced via path deduplication.
	DeduplicatedFrom *string `protobuf:"bytes,11,opt,name=deduplicated_from,json=deduplicatedFrom,proto3,oneof" json:"deduplicated_from,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MediaItem) Reset() {
	*x = MediaItem{}
	mi := &file_media_set_media_set_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItem) ProtoMessage() {}

func (x *MediaItem) ProtoReflect() protoreflect.Message {
	mi := &file_media_set_media_set_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItem.ProtoReflect.Descriptor instead.
func (*MediaItem) Descriptor() ([]byte, []int) {
	return file_media_set_media_set_proto_rawDescGZIP(), []int{1}
}

func (x *MediaItem) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *MediaItem) GetMediaSetRid() string {
	if x != nil {
		return x.MediaSetRid
	}
	return ""
}

func (x *MediaItem) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *MediaItem) GetTransactionRid() string {
	if x != nil {
		return x.TransactionRid
	}
	return ""
}

func (x *MediaItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MediaItem) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MediaItem) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *MediaItem) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *MediaItem) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *MediaItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MediaItem) GetDeduplicatedFrom() string {
	if x != nil && x.DeduplicatedFrom != nil {
		return *x.DeduplicatedFrom
	}
	return ""
}

// A write batch on a transactional media set branch.
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           string                 `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	MediaSetRid   string                 `protobuf:"bytes,2,opt,name=media_set_rid,json=mediaSetRid,proto3" json:"media_set_rid,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	State         TransactionState       `protobuf:"varint,4,opt,name=state,proto3,enum=open_foundry.media_set.TransactionState" json:"state,omitempty"`
	OpenedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=opened_at,json=openedAt,proto3" json:"opened_at,omitempty"`
	ClosedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	OpenedBy      string                 `protobuf:"bytes,7,opt,name=opened_by,json=openedBy,proto3" json:"opened_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_media_set_media_set_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_media_set_media_set_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_media_set_media_set_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *Transaction) GetMediaSetRid() string {
	if x != nil {
		return x.MediaSetRid
	}
	return ""
}

func (x *Transaction) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Transaction) GetState() TransactionState {
	if x != nil {
		return x.State
	}
	return TransactionState_TRANSACTION_STATE_UNSPECIFIED
}

func (x *Transaction) GetOpenedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenedAt
	}
	return nil
}

func (x *Transaction) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *Transaction) GetOpenedBy() string {
	if x != nil {
		return x.OpenedBy
	}
	return ""
}

var File_media_set_media_set_proto protoreflect.FileDescriptor

const file_media_set_media_set_proto_rawDesc = "" +
	"\n" +
	"\x19media_set/media_set.proto\x12\x16open_foundry.media_set\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x04\n" +
	"\bMediaSet\x12\x10\n" +
	"\x03rid\x18\x01 \x01(\tR\x03rid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vproject_rid\x18\x03 \x01(\tR\n" +
	"projectRid\x12>\n" +
	"\x06schema\x18\x04 \x01(\x0e2&.open_foundry.media_set.MediaSetSchemaR\x06schema\x12,\n" +
	"\x12allowed_mime_types\x18\x05 \x03(\tR\x10allowedMimeTypes\x12X\n" +
	"\x12transaction_policy\x18\x06 \x01(\x0e2).open_foundry.media_set.TransactionPolicyR\x11transactionPolicy\x12+\n" +
	"\x11retention_seconds\x18\a \x01(\x03R\x10retentionSeconds\x12\x18\n" +
	"\avirtual\x18\b \x01(\bR\avirtual\x12\"\n" +
	"\n" +
	"source_rid\x18\t \x01(\tH\x00R\tsourceRid\x88\x01\x01\x12\x1a\n" +
	"\bmarkings\x18\n" +
	" \x03(\tR\bmarkings\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\f \x01(\tR\tcreatedByB\r\n" +
	"\v_source_rid\"\x89\x03\n" +
	"\tMediaItem\x12\x10\n" +
	"\x03rid\x18\x01 \x01(\tR\x03rid\x12\"\n" +
	"\rmedia_set_rid\x18\x02 \x01(\tR\vmediaSetRid\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12'\n" +
	"\x0ftransaction_rid\x18\x04 \x01(\tR\x0etransactionRid\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\b \x01(\tR\x06sha256\x12\x1a\n" +
	"\bmetadata\x18\t \x01(\tR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x120\n" +
	"\x11deduplicated_from\x18\v \x01(\tH\x00R\x10deduplicatedFrom\x88\x01\x01B\x14\n" +
	"\x12_deduplicated_from\"\xaa\x02\n" +
	"\vTransaction\x12\x10\n" +
	"\x03rid\x18\x01 \x01(\tR\x03rid\x12\"\n" +
	"\rmedia_set_rid\x18\x02 \x01(\tR\vmediaSetRid\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12>\n" +
	"\x05state\x18\x04 \x01(\x0e2(.open_foundry.media_set.TransactionStateR\x05state\x127\n" +
	"\topened_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bopenedAt\x127\n" +
	"\tclosed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\x12\x1b\n" +
	"\topened_by\x18\a \x01(\tR\bopenedBy*\xe3\x01\n" +
	"\x0eMediaSetSchema\x12 \n" +
	"\x1cMEDIA_SET_SCHEMA_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MEDIA_SET_SCHEMA_IMAGE\x10\x01\x12\x1a\n" +
	"\x16MEDIA_SET_SCHEMA_AUDIO\x10\x02\x12\x1a\n" +
	"\x16MEDIA_SET_SCHEMA_VIDEO\x10\x03\x12\x1d\n" +
	"\x19MEDIA_SET_SCHEMA_DOCUMENT\x10\x04\x12 \n" +
	"\x1cMEDIA_SET_SCHEMA_SPREADSHEET\x10\x05\x12\x1a\n" +
	"\x16MEDIA_SET_SCHEMA_EMAIL\x10\x06*\x85\x01\n" +
	"\x11TransactionPolicy\x12\"\n" +
	"\x1eTRANSACTION_POLICY_UNSPECIFIED\x10\x00\x12&\n" +
	"\"TRANSACTION_POLICY_TRANSACTIONLESS\x10\x01\x12$\n" +
	" TRANSACTION_POLICY_TRANSACTIONAL\x10\x02*\x91\x01\n" +
	"\x10TransactionState\x12!\n" +
	"\x1dTRANSACTION_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TRANSACTION_STATE_OPEN\x10\x01\x12\x1f\n" +
	"\x1bTRANSACTION_STATE_COMMITTED\x10\x02\x12\x1d\n" +
	"\x19TRANSACTION_STATE_ABORTED\x10\x03b\x06proto3"

var (
	file_media_set_media_set_proto_rawDescOnce sync.Once
	file_media_set_media_set_proto_rawDescData []byte
)

func file_media_set_media_set_proto_rawDescGZIP() []byte {
	file_media_set_media_set_proto_rawDescOnce.Do(func() {
		file_media_set_media_set_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_set_media_set_proto_rawDesc), len(file_media_set_media_set_proto_rawDesc)))
	})
	return file_media_set_media_set_proto_rawDescData
}

var file_media_set_media_set_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_media_set_media_set_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_media_set_media_set_proto_goTypes = []any{
	(MediaSetSchema)(0),           // 0: open_foundry.media_set.MediaSetSchema
	(TransactionPolicy)(0),        // 1: open_foundry.media_set.TransactionPolicy
	(TransactionState)(0),         // 2: open_foundry.media_set.TransactionState
	(*MediaSet)(nil),              // 3: open_foundry.media_set.MediaSet
	(*MediaItem)(nil),             // 4: open_foundry.media_set.MediaItem
	(*Transaction)(nil),           // 5: open_foundry.media_set.Transaction
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_media_set_media_set_proto_depIdxs = []int32{
	0, // 0: open_foundry.media_set.MediaSet.schema:type_name -> open_foundry.media_set.MediaSetSchema
	1, // 1: open_foundry.media_set.MediaSet.transaction_policy:type_name -> open_foundry.media_set.TransactionPolicy
	6, // 2: open_foundry.media_set.MediaSet.created_at:type_name -> google.protobuf.Timestamp
	6, // 3: open_foundry.media_set.MediaItem.created_at:type_name -> google.protobuf.Timestamp
	2, // 4: open_foundry.media_set.Transaction.state:type_name -> open_foundry.media_set.TransactionState
	6, // 5: open_foundry.media_set.Transaction.opened_at:type_name -> google.protobuf.Timestamp
	6, // 6: open_foundry.media_set.Transaction.closed_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_media_set_media_set_proto_init() }
func file_media_set_media_set_proto_init() {
	if File_media_set_media_set_proto != nil {
		return
	}
	file_media_set_media_set_proto_msgTypes[0].OneofWrappers = []any{}
	file_media_set_media_set_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_set_media_set_proto_rawDesc), len(file_media_set_media_set_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_set_media_set_proto_goTypes,
		DependencyIndexes: file_media_set_media_set_proto_depIdxs,
		EnumInfos:         file_media_set_media_set_proto_enumTypes,
		MessageInfos:      file_media_set_media_set_proto_msgTypes,
	}.Build()
	File_media_set_media_set_proto = out.File
	file_media_set_media_set_proto_goTypes = nil
	file_media_set_media_set_proto_depIdxs = nil
}
