// Command of-sdk-gen is the OpenFoundry SDK generator.
//
// It reads a service's `internal/openapi/openapi.yaml`, shells out to the
// language-specific generator (openapi-typescript-codegen for TypeScript,
// openapi-python-client for Python), and writes a working client into the
// requested output directory. No code is generated by this Go binary
// itself — it is a thin orchestrator so we can keep the toolchain
// dependency out of `go.mod` (Node lives in CI as a system tool).
//
// Usage:
//
//	of-sdk-gen --service <name> --lang ts|py --out <dir>
//	  [--repo-root <path>] [--spec <explicit-yaml-path>]
//
// Exit codes:
//
//	0  success
//	2  bad flags / missing spec
//	3  underlying generator failed (stderr forwarded)
package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
)

const usage = `of-sdk-gen — generate language SDKs from service OpenAPI specs

Required flags:
  --service NAME       service directory name under services/
  --lang   ts|py       target language
  --out    DIR         output directory (created if missing)

Optional flags:
  --repo-root PATH     repo root (default: walk up from --service)
  --spec      PATH     explicit OpenAPI spec path (overrides service lookup)
  --client    NAME     ts client kind (default: fetch)

The Node / Python generators must be installed and on PATH:
  npx openapi-typescript-codegen --version
  openapi-python-client --version
`

type options struct {
	service  string
	lang     string
	out      string
	repoRoot string
	spec     string
	client   string
}

func main() {
	opts, err := parseFlags(os.Args[1:])
	if err != nil {
		if errors.Is(err, flag.ErrHelp) {
			fmt.Fprint(os.Stdout, usage)
			os.Exit(0)
		}
		fmt.Fprintf(os.Stderr, "of-sdk-gen: %v\n\n%s", err, usage)
		os.Exit(2)
	}
	if err := run(opts, os.Stdout, os.Stderr); err != nil {
		fmt.Fprintf(os.Stderr, "of-sdk-gen: %v\n", err)
		os.Exit(3)
	}
}

func parseFlags(args []string) (options, error) {
	fs := flag.NewFlagSet("of-sdk-gen", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	var opts options
	fs.StringVar(&opts.service, "service", "", "service directory name")
	fs.StringVar(&opts.lang, "lang", "", "target language (ts|py)")
	fs.StringVar(&opts.out, "out", "", "output directory")
	fs.StringVar(&opts.repoRoot, "repo-root", "", "repository root (optional)")
	fs.StringVar(&opts.spec, "spec", "", "explicit OpenAPI spec path (optional)")
	fs.StringVar(&opts.client, "client", "fetch", "ts client kind (default fetch)")
	if err := fs.Parse(args); err != nil {
		return options{}, err
	}
	if opts.out == "" {
		return options{}, errors.New("--out is required")
	}
	if opts.lang != "ts" && opts.lang != "py" {
		return options{}, fmt.Errorf("--lang must be 'ts' or 'py', got %q", opts.lang)
	}
	if opts.spec == "" && opts.service == "" {
		return options{}, errors.New("either --service or --spec is required")
	}
	return opts, nil
}

func run(opts options, stdout, stderr io.Writer) error {
	spec, err := resolveSpec(opts)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(opts.out, 0o755); err != nil {
		return fmt.Errorf("mkdir out: %w", err)
	}
	switch opts.lang {
	case "ts":
		return runTypeScript(spec, opts.out, opts.client, stdout, stderr)
	case "py":
		return runPython(spec, opts.out, stdout, stderr)
	default:
		return fmt.Errorf("unsupported lang %q", opts.lang)
	}
}

// resolveSpec returns the absolute path to the OpenAPI YAML to feed the
// generator. The order is: explicit --spec wins, otherwise resolve
// services/<svc>/internal/openapi/openapi.yaml relative to --repo-root,
// then walking up from CWD.
func resolveSpec(opts options) (string, error) {
	if opts.spec != "" {
		return abs(opts.spec)
	}
	root := opts.repoRoot
	if root == "" {
		found, err := findRepoRoot()
		if err != nil {
			return "", err
		}
		root = found
	}
	p := filepath.Join(root, "services", opts.service, "internal", "openapi", "openapi.yaml")
	if _, err := os.Stat(p); err != nil {
		return "", fmt.Errorf("spec not found at %s: %w", p, err)
	}
	return p, nil
}

func abs(p string) (string, error) {
	a, err := filepath.Abs(p)
	if err != nil {
		return "", err
	}
	if _, err := os.Stat(a); err != nil {
		return "", fmt.Errorf("spec %s: %w", a, err)
	}
	return a, nil
}

// findRepoRoot walks up from CWD looking for a go.mod marker.
func findRepoRoot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	dir := cwd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("repo root (go.mod) not found from %s", cwd)
		}
		dir = parent
	}
}

// runTypeScript invokes openapi-typescript-codegen via npx.
//
// Command shape kept verbatim per the task brief:
//
//	npx --yes openapi-typescript-codegen --input <spec> --output <out> --client fetch
//
// `--yes` is passed so CI doesn't get stuck on the npm prompt the first
// time the package is fetched.
func runTypeScript(spec, out, client string, stdout, stderr io.Writer) error {
	bin, err := exec.LookPath("npx")
	if err != nil {
		return fmt.Errorf("npx not on PATH (install Node 18+): %w", err)
	}
	cmd := exec.Command(bin, "--yes", "openapi-typescript-codegen",
		"--input", spec,
		"--output", out,
		"--client", client,
	)
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("openapi-typescript-codegen failed: %w", err)
	}
	return nil
}

// runPython invokes openapi-python-client; the binary must be on PATH
// (pip install openapi-python-client).
func runPython(spec, out string, stdout, stderr io.Writer) error {
	bin, err := exec.LookPath("openapi-python-client")
	if err != nil {
		return fmt.Errorf("openapi-python-client not on PATH (pip install openapi-python-client): %w", err)
	}
	// openapi-python-client wants a non-existing output directory; if
	// `out` was just created empty by our caller, delete it back before
	// invoking the tool so it can write fresh.
	if entries, _ := os.ReadDir(out); len(entries) == 0 {
		_ = os.Remove(out)
	}
	cmd := exec.Command(bin, "generate", "--path", spec, "--output-path", out, "--overwrite")
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("openapi-python-client failed: %w", err)
	}
	return nil
}
