{{- if .Values.enabled -}}
{{- if .Values.configserver.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vespa.configserver.fullname" . }}
  labels:
{{ include "vespa.labels" . | indent 4 }}
    app.kubernetes.io/component: vespa-configserver
spec:
  minAvailable: {{ .Values.configserver.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
{{ include "vespa.configserver.selectorLabels" . | indent 6 }}
{{- end }}
{{- if .Values.content.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vespa.content.fullname" . }}
  labels:
{{ include "vespa.labels" . | indent 4 }}
    app.kubernetes.io/component: vespa-content
spec:
  minAvailable: {{ .Values.content.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
{{ include "vespa.content.selectorLabels" . | indent 6 }}
{{- end }}
{{- end }}
