#[path = "../../identity-federation-service/src/models/api_key.rs"]
pub mod api_key;
#[path = "../../identity-federation-service/src/models/control_panel.rs"]
pub mod control_panel;
#[path = "../../identity-federation-service/src/models/mfa.rs"]
pub mod mfa;
#[path = "../../identity-federation-service/src/models/role.rs"]
pub mod role;
#[path = "../../identity-federation-service/src/models/session.rs"]
pub mod session;
#[path = "../../identity-federation-service/src/models/sso.rs"]
pub mod sso;
#[path = "../../identity-federation-service/src/models/user.rs"]
pub mod user;
