use serde_json::Value;

use crate::models::notepad::{NotepadDocument, NotepadExportPayload};

pub fn cleanup_stale_presence_sql() -> &'static str {
    "DELETE FROM notepad_presence WHERE last_seen_at < NOW() - INTERVAL '5 minutes'"
}

pub fn render_export_payload(document: &NotepadDocument) -> NotepadExportPayload {
    let title = document.title.trim();
    let html = render_document_html(document);
    let preview_excerpt = document
        .content
        .lines()
        .map(str::trim)
        .find(|line| !line.is_empty())
        .unwrap_or("Document export")
        .chars()
        .take(180)
        .collect::<String>();

    NotepadExportPayload {
        file_name: format!("{}.html", slugify(title)),
        mime_type: "text/html".to_string(),
        title: title.to_string(),
        html,
        preview_excerpt,
    }
}

pub fn render_document_html(document: &NotepadDocument) -> String {
    let widgets_html = render_widgets(&document.widgets);
    let description = if document.description.trim().is_empty() {
        String::new()
    } else {
        format!(
            "<p class=\"lede\">{}</p>",
            escape_html(document.description.trim())
        )
    };

    format!(
        "<!doctype html><html><head><meta charset=\"utf-8\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" /><title>{title}</title><style>{style}</style></head><body><article class=\"document\"><header><div class=\"eyebrow\">Notepad</div><h1>{title}</h1>{description}</header><section class=\"content\">{content}</section>{widgets}<footer>Generated by OpenFoundry Notepad</footer></article></body></html>",
        title = escape_html(document.title.trim()),
        style = base_styles(),
        description = description,
        content = render_markdown(&document.content),
        widgets = widgets_html,
    )
}

fn render_widgets(widgets: &Value) -> String {
    let Some(entries) = widgets.as_array() else {
        return String::new();
    };

    if entries.is_empty() {
        return String::new();
    }

    let cards = entries
        .iter()
        .map(|widget| {
            let title = widget
                .get("title")
                .and_then(Value::as_str)
                .unwrap_or("Embedded widget");
            let kind = widget
                .get("kind")
                .and_then(Value::as_str)
                .unwrap_or("widget");
            let summary = widget
                .get("summary")
                .and_then(Value::as_str)
                .unwrap_or("Live content rendered in the OpenFoundry workspace.");

            format!(
                "<div class=\"widget-card\"><div class=\"widget-kind\">{kind}</div><h3>{title}</h3><p>{summary}</p></div>",
                kind = escape_html(kind),
                title = escape_html(title),
                summary = escape_html(summary)
            )
        })
        .collect::<Vec<_>>()
        .join("");

    format!(
        "<section class=\"widgets\"><div class=\"section-label\">Embedded widgets</div><div class=\"widget-grid\">{cards}</div></section>"
    )
}

fn render_markdown(markdown: &str) -> String {
    let mut html = String::new();
    let mut in_list = false;

    for raw_line in markdown.lines() {
        let line = raw_line.trim_end();
        let trimmed = line.trim();

        if trimmed.is_empty() {
            if in_list {
                html.push_str("</ul>");
                in_list = false;
            }
            continue;
        }

        if let Some(content) = trimmed.strip_prefix("### ") {
            if in_list {
                html.push_str("</ul>");
                in_list = false;
            }
            html.push_str(&format!("<h3>{}</h3>", escape_html(content)));
            continue;
        }

        if let Some(content) = trimmed.strip_prefix("## ") {
            if in_list {
                html.push_str("</ul>");
                in_list = false;
            }
            html.push_str(&format!("<h2>{}</h2>", escape_html(content)));
            continue;
        }

        if let Some(content) = trimmed.strip_prefix("# ") {
            if in_list {
                html.push_str("</ul>");
                in_list = false;
            }
            html.push_str(&format!("<h1>{}</h1>", escape_html(content)));
            continue;
        }

        if let Some(content) = trimmed.strip_prefix("- ") {
            if !in_list {
                html.push_str("<ul>");
                in_list = true;
            }
            html.push_str(&format!("<li>{}</li>", escape_html(content)));
            continue;
        }

        if in_list {
            html.push_str("</ul>");
            in_list = false;
        }

        html.push_str(&format!("<p>{}</p>", escape_html(trimmed)));
    }

    if in_list {
        html.push_str("</ul>");
    }

    html
}

fn slugify(value: &str) -> String {
    let slug = value
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect::<String>();
    slug.trim_matches('-').to_string()
}

fn escape_html(input: &str) -> String {
    input
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

fn base_styles() -> &'static str {
    "body{margin:0;background:#f8fafc;color:#0f172a;font:16px/1.65 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif;} .document{max-width:900px;margin:0 auto;padding:56px 28px 96px;} .eyebrow{font-size:12px;letter-spacing:.24em;text-transform:uppercase;color:#0f766e;font-weight:700;} h1,h2,h3{line-height:1.15;color:#020617;} h1{font-size:44px;margin:12px 0 16px;} h2{font-size:28px;margin:32px 0 12px;} h3{font-size:20px;margin:24px 0 8px;} p,li{color:#334155;} .lede{font-size:18px;color:#475569;margin-bottom:24px;} ul{padding-left:22px;} .widgets{margin-top:40px;} .section-label{font-size:12px;letter-spacing:.2em;text-transform:uppercase;color:#475569;font-weight:700;margin-bottom:12px;} .widget-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px;} .widget-card{border:1px solid #cbd5e1;border-radius:18px;padding:18px;background:white;box-shadow:0 10px 30px rgba(15,23,42,.06);} .widget-kind{font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#0284c7;font-weight:700;margin-bottom:8px;} footer{margin-top:48px;padding-top:20px;border-top:1px solid #e2e8f0;color:#64748b;font-size:13px;}"
}
