// Package service hosts password hashing + JWT issuance for slice 1.
package service

import (
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"

	"golang.org/x/crypto/argon2"
)

// Argon2id parameters — sane defaults matching the Rust crate's
// `argon2::Argon2::default()` (memory=19 MiB, time=2, parallelism=1).
// Output: PHC string `$argon2id$v=19$m=...,t=...,p=...$<salt>$<hash>`.
const (
	argonTime    uint32 = 2
	argonMemory  uint32 = 19 * 1024
	argonThreads uint8  = 1
	argonKeyLen  uint32 = 32
	argonSaltLen        = 16
)

// HashPassword returns the PHC-encoded argon2id hash.
//
// PHC format is the same encoding used by the Rust `argon2` crate so
// hashes generated by either side validate against the other. This
// matters for production cutover: a user registered via the Rust
// service can still log in via the Go service and vice versa.
func HashPassword(password string) (string, error) {
	salt := make([]byte, argonSaltLen)
	if _, err := rand.Read(salt); err != nil {
		return "", fmt.Errorf("generate salt: %w", err)
	}
	hash := argon2.IDKey([]byte(password), salt, argonTime, argonMemory, argonThreads, argonKeyLen)

	enc := base64.RawStdEncoding
	return fmt.Sprintf(
		"$argon2id$v=19$m=%d,t=%d,p=%d$%s$%s",
		argonMemory, argonTime, argonThreads,
		enc.EncodeToString(salt),
		enc.EncodeToString(hash),
	), nil
}

// VerifyPassword parses a PHC-encoded argon2id hash and constant-time
// compares the recomputed hash. Returns ErrPasswordMismatch on miss
// (never nil-with-false to keep the API ergonomic).
func VerifyPassword(password, encoded string) error {
	parts := strings.Split(encoded, "$")
	// expected: "" / "argon2id" / "v=19" / "m=,t=,p=" / salt / hash
	if len(parts) != 6 || parts[1] != "argon2id" {
		return ErrInvalidHash
	}
	var version int
	if _, err := fmt.Sscanf(parts[2], "v=%d", &version); err != nil {
		return ErrInvalidHash
	}
	var m, t uint32
	var p uint8
	if _, err := fmt.Sscanf(parts[3], "m=%d,t=%d,p=%d", &m, &t, &p); err != nil {
		return ErrInvalidHash
	}
	enc := base64.RawStdEncoding
	salt, err := enc.DecodeString(parts[4])
	if err != nil {
		return ErrInvalidHash
	}
	want, err := enc.DecodeString(parts[5])
	if err != nil {
		return ErrInvalidHash
	}
	got := argon2.IDKey([]byte(password), salt, t, m, p, uint32(len(want)))
	if subtle.ConstantTimeCompare(got, want) != 1 {
		return ErrPasswordMismatch
	}
	return nil
}

// HashRefreshToken returns a SHA-256 hex digest of the opaque refresh
// token. The plaintext goes to the client; only the digest is stored.
func HashRefreshToken(plaintext string) string {
	sum := sha256.Sum256([]byte(plaintext))
	return hex.EncodeToString(sum[:])
}

// NewRefreshTokenPlaintext returns a 256-bit URL-safe base64 token.
// The lookup column stores its SHA-256 digest.
func NewRefreshTokenPlaintext() (string, error) {
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("rand: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

// ErrPasswordMismatch is returned by VerifyPassword on a hash miss.
var ErrPasswordMismatch = errors.New("password mismatch")

// ErrInvalidHash is returned by VerifyPassword when the encoding is malformed.
var ErrInvalidHash = errors.New("invalid argon2 hash encoding")
