{{- if .Values.enabled -}}
{{- if not .Values.realm.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iceberg-catalog.realmSecretName" . }}
  labels:
{{ include "iceberg-catalog.labels" . | indent 4 }}
type: Opaque
stringData:
  client-id: {{ .Values.realm.rootClientId | quote }}
  client-secret: {{ required "realm.rootClientSecret is required when realm.existingSecret is empty" .Values.realm.rootClientSecret | quote }}
---
{{- end }}
{{- if and (not .Values.postgres.existingSecret) (not .Values.postgres.cnpg.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iceberg-catalog.postgresSecretName" . }}
  labels:
{{ include "iceberg-catalog.labels" . | indent 4 }}
type: Opaque
stringData:
  {{ .Values.postgres.passwordSecretKey }}: {{ required "postgres.password is required when postgres.existingSecret is empty and CNPG is disabled" .Values.postgres.password | quote }}
{{- end }}
{{- end }}
