// This file is generated by `cargo run -p of-cli -- docs generate-sdk-typescript`.
// Do not edit manually.

import { createContext, createElement, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { OpenFoundryClient, type OpenFoundryClientOptions } from './index';

export interface OpenFoundryProviderProps {
  client?: OpenFoundryClient;
  options?: OpenFoundryClientOptions;
  children?: ReactNode;
}

export interface OpenFoundryQueryState<T> {
  data: T | null;
  error: Error | null;
  loading: boolean;
  refetch: () => Promise<T | null>;
}

export interface OpenFoundryQueryOptions<T> {
  enabled?: boolean;
  initialData?: T | null;
  preservePreviousData?: boolean;
}

export interface OpenFoundryMutationState<TResult, TArgs extends unknown[]> {
  loading: boolean;
  error: Error | null;
  lastResult: TResult | null;
  mutate: (...args: TArgs) => Promise<TResult>;
  reset: () => void;
}

export interface OpenFoundryMutationOptions<TResult> {
  onSuccess?: (result: TResult) => void;
  onError?: (error: Error) => void;
}

const OpenFoundryContext = createContext<OpenFoundryClient | null>(null);

export function OpenFoundryProvider(props: OpenFoundryProviderProps) {
  const headersKey = stableSerialize(props.options?.headers ?? {});
  const client = useMemo(() => {
    if (props.client) {
      return props.client;
    }
    if (!props.options) {
      throw new Error('OpenFoundryProvider requires either a client or options');
    }
    return new OpenFoundryClient(props.options);
  }, [props.client, props.options?.baseUrl, props.options?.fetch, headersKey]);
  return createElement(OpenFoundryContext.Provider, { value: client }, props.children);
}

export function useOpenFoundry(): OpenFoundryClient {
  const client = useContext(OpenFoundryContext);
  if (!client) {
    throw new Error('OpenFoundryProvider is missing from the React tree');
  }
  return client;
}

export function useOpenFoundryClient(options: OpenFoundryClientOptions): OpenFoundryClient {
  const headersKey = stableSerialize(options.headers ?? {});
  return useMemo(
    () => new OpenFoundryClient(options),
    [options.baseUrl, options.fetch, headersKey],
  );
}

export function useOpenFoundryQuery<T>(
  fetcher: () => Promise<T>,
  deps: readonly unknown[] = [],
  options: OpenFoundryQueryOptions<T> = {},
): OpenFoundryQueryState<T> {
  const fetcherRef = useRef(fetcher);
  fetcherRef.current = fetcher;
  const enabled = options.enabled ?? true;
  const [data, setData] = useState<T | null>(options.initialData ?? null);
  const [error, setError] = useState<Error | null>(null);
  const [loading, setLoading] = useState(enabled);

  const refetch = async (): Promise<T | null> => {
    if (!enabled) {
      setLoading(false);
      return data;
    }
    setLoading(true);
    setError(null);
    try {
      const result = await fetcherRef.current();
      setData(result);
      return result;
    } catch (cause) {
      const nextError = cause instanceof Error ? cause : new Error('OpenFoundry query failed');
      setError(nextError);
      return null;
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!enabled) {
      setLoading(false);
      return;
    }
    if (!options.preservePreviousData && options.initialData === undefined) {
      setData(null);
    }
    void refetch();
  }, [enabled, ...deps]);

  return { data, error, loading, refetch };
}

export function useOpenFoundryMutation<TResult, TArgs extends unknown[]>(
  mutation: (...args: TArgs) => Promise<TResult>,
  options: OpenFoundryMutationOptions<TResult> = {},
): OpenFoundryMutationState<TResult, TArgs> {
  const mutationRef = useRef(mutation);
  mutationRef.current = mutation;
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);
  const [lastResult, setLastResult] = useState<TResult | null>(null);

  return {
    loading,
    error,
    lastResult,
    mutate: async (...args: TArgs): Promise<TResult> => {
      setLoading(true);
      setError(null);
      try {
        const result = await mutationRef.current(...args);
        setLastResult(result);
        options.onSuccess?.(result);
        return result;
      } catch (cause) {
        const nextError = cause instanceof Error ? cause : new Error('OpenFoundry mutation failed');
        setError(nextError);
        options.onError?.(nextError);
        throw nextError;
      } finally {
        setLoading(false);
      }
    },
    reset: () => {
      setError(null);
      setLastResult(null);
    },
  };
}

export function createOpenFoundryQueryKey(...parts: unknown[]): string {
  return stableSerialize(parts);
}

function stableSerialize(value: unknown): string {
  if (value === null || value === undefined) {
    return '';
  }
  try {
    return JSON.stringify(value, Object.keys(value as Record<string, unknown>).sort());
  } catch (_error) {
    return '';
  }
}
