# This file is generated by `cargo run -p of-cli -- docs generate-sdk-python`.
# Do not edit manually.
from __future__ import annotations

from typing import Any, Mapping

from .client import OpenFoundryClient

MCP_TOOL_REGISTRY: list[dict[str, Any]] = [
    {
        "name": "openfoundry.auth.assignrole",
        "description": "Generated from `open_foundry.auth` RPC `AssignRole` in service `RbacService`.",
        "operation_id": "open_foundry.auth.RbacService.AssignRole",
        "method": "POST",
        "path": "/api/v1/auth/assign-role",
        "namespace": "auth",
        "namespace_member": "assignrole",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/AssignRoleRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.auth.getme",
        "description": "Generated from `open_foundry.auth` RPC `GetMe` in service `AuthService`.",
        "operation_id": "open_foundry.auth.AuthService.GetMe",
        "method": "GET",
        "path": "/api/v1/auth/get-me",
        "namespace": "auth",
        "namespace_member": "getme",
        "input_schema":
            {
              "properties": {},
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.auth.listroles",
        "description": "Generated from `open_foundry.auth` RPC `ListRoles` in service `RbacService`.",
        "operation_id": "open_foundry.auth.RbacService.ListRoles",
        "method": "GET",
        "path": "/api/v1/auth/list-roles",
        "namespace": "auth",
        "namespace_member": "listroles",
        "input_schema":
            {
              "properties": {},
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.auth.login",
        "description": "Generated from `open_foundry.auth` RPC `Login` in service `AuthService`.",
        "operation_id": "open_foundry.auth.AuthService.Login",
        "method": "POST",
        "path": "/api/v1/auth/login",
        "namespace": "auth",
        "namespace_member": "login",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/LoginRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.auth.refreshtoken",
        "description": "Generated from `open_foundry.auth` RPC `RefreshToken` in service `AuthService`.",
        "operation_id": "open_foundry.auth.AuthService.RefreshToken",
        "method": "POST",
        "path": "/api/v1/auth/refresh-token",
        "namespace": "auth",
        "namespace_member": "refreshtoken",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/RefreshRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.auth.register",
        "description": "Generated from `open_foundry.auth` RPC `Register` in service `AuthService`.",
        "operation_id": "open_foundry.auth.AuthService.Register",
        "method": "POST",
        "path": "/api/v1/auth/register",
        "namespace": "auth",
        "namespace_member": "register",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/RegisterRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.common.check",
        "description": "Generated from `open_foundry.common` RPC `Check` in service `HealthService`.",
        "operation_id": "open_foundry.common.HealthService.Check",
        "method": "POST",
        "path": "/api/v1/common/check",
        "namespace": "common",
        "namespace_member": "check",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/HealthCheckRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.dataIntegration.createconnection",
        "description": "Generated from `open_foundry.data_integration` RPC `CreateConnection` in service `ConnectorService`.",
        "operation_id": "open_foundry.data_integration.ConnectorService.CreateConnection",
        "method": "POST",
        "path": "/api/v1/data-integration/create-connection",
        "namespace": "dataIntegration",
        "namespace_member": "createconnection",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/CreateConnectionRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.dataIntegration.deleteconnection",
        "description": "Generated from `open_foundry.data_integration` RPC `DeleteConnection` in service `ConnectorService`.",
        "operation_id": "open_foundry.data_integration.ConnectorService.DeleteConnection",
        "method": "DELETE",
        "path": "/api/v1/data-integration/delete-connection",
        "namespace": "dataIntegration",
        "namespace_member": "deleteconnection",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "id": {
                      "$ref": "#/components/schemas/Uuid"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.dataIntegration.inferschema",
        "description": "Generated from `open_foundry.data_integration` RPC `InferSchema` in service `ConnectorService`.",
        "operation_id": "open_foundry.data_integration.ConnectorService.InferSchema",
        "method": "POST",
        "path": "/api/v1/data-integration/infer-schema",
        "namespace": "dataIntegration",
        "namespace_member": "inferschema",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/InferSchemaRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.dataIntegration.listconnections",
        "description": "Generated from `open_foundry.data_integration` RPC `ListConnections` in service `ConnectorService`.",
        "operation_id": "open_foundry.data_integration.ConnectorService.ListConnections",
        "method": "GET",
        "path": "/api/v1/data-integration/list-connections",
        "namespace": "dataIntegration",
        "namespace_member": "listconnections",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "pagination": {
                      "$ref": "#/components/schemas/PageRequest"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.dataIntegration.syncconnection",
        "description": "Generated from `open_foundry.data_integration` RPC `SyncConnection` in service `ConnectorService`.",
        "operation_id": "open_foundry.data_integration.ConnectorService.SyncConnection",
        "method": "POST",
        "path": "/api/v1/data-integration/sync-connection",
        "namespace": "dataIntegration",
        "namespace_member": "syncconnection",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/SyncConnectionRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.dataIntegration.testconnection",
        "description": "Generated from `open_foundry.data_integration` RPC `TestConnection` in service `ConnectorService`.",
        "operation_id": "open_foundry.data_integration.ConnectorService.TestConnection",
        "method": "POST",
        "path": "/api/v1/data-integration/test-connection",
        "namespace": "dataIntegration",
        "namespace_member": "testconnection",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/TestConnectionRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.dataset.createdataset",
        "description": "Generated from `open_foundry.dataset` RPC `CreateDataset` in service `DatasetService`.",
        "operation_id": "open_foundry.dataset.DatasetService.CreateDataset",
        "method": "POST",
        "path": "/api/v1/datasets/create-dataset",
        "namespace": "dataset",
        "namespace_member": "createdataset",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/CreateDatasetRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.dataset.deletedataset",
        "description": "Generated from `open_foundry.dataset` RPC `DeleteDataset` in service `DatasetService`.",
        "operation_id": "open_foundry.dataset.DatasetService.DeleteDataset",
        "method": "DELETE",
        "path": "/api/v1/datasets/delete-dataset",
        "namespace": "dataset",
        "namespace_member": "deletedataset",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "id": {
                      "$ref": "#/components/schemas/Uuid"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.dataset.getdataset",
        "description": "Generated from `open_foundry.dataset` RPC `GetDataset` in service `DatasetService`.",
        "operation_id": "open_foundry.dataset.DatasetService.GetDataset",
        "method": "GET",
        "path": "/api/v1/datasets/get-dataset",
        "namespace": "dataset",
        "namespace_member": "getdataset",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "id": {
                      "$ref": "#/components/schemas/Uuid"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.dataset.getversions",
        "description": "Generated from `open_foundry.dataset` RPC `GetVersions` in service `DatasetService`.",
        "operation_id": "open_foundry.dataset.DatasetService.GetVersions",
        "method": "GET",
        "path": "/api/v1/datasets/get-versions",
        "namespace": "dataset",
        "namespace_member": "getversions",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "dataset_id": {
                      "$ref": "#/components/schemas/Uuid"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.dataset.listdatasets",
        "description": "Generated from `open_foundry.dataset` RPC `ListDatasets` in service `DatasetService`.",
        "operation_id": "open_foundry.dataset.DatasetService.ListDatasets",
        "method": "GET",
        "path": "/api/v1/datasets/list-datasets",
        "namespace": "dataset",
        "namespace_member": "listdatasets",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "pagination": {
                      "$ref": "#/components/schemas/PageRequest"
                    },
                    "search": {
                      "type": "string"
                    },
                    "tags": {
                      "items": {
                        "type": "string"
                      },
                      "type": "array"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.dataset.previewdata",
        "description": "Generated from `open_foundry.dataset` RPC `PreviewData` in service `DatasetService`.",
        "operation_id": "open_foundry.dataset.DatasetService.PreviewData",
        "method": "POST",
        "path": "/api/v1/datasets/preview-data",
        "namespace": "dataset",
        "namespace_member": "previewdata",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/PreviewDataRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.dataset.updatedataset",
        "description": "Generated from `open_foundry.dataset` RPC `UpdateDataset` in service `DatasetService`.",
        "operation_id": "open_foundry.dataset.DatasetService.UpdateDataset",
        "method": "PATCH",
        "path": "/api/v1/datasets/update-dataset",
        "namespace": "dataset",
        "namespace_member": "updatedataset",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/UpdateDatasetRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.notebook.createnotebook",
        "description": "Generated from `notebook` RPC `CreateNotebook` in service `NotebookService`.",
        "operation_id": "notebook.NotebookService.CreateNotebook",
        "method": "POST",
        "path": "/api/v1/notebook/create-notebook",
        "namespace": "notebook",
        "namespace_member": "createnotebook",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/CreateNotebookRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.notebook.createsession",
        "description": "Generated from `notebook` RPC `CreateSession` in service `KernelService`.",
        "operation_id": "notebook.KernelService.CreateSession",
        "method": "POST",
        "path": "/api/v1/notebook/create-session",
        "namespace": "notebook",
        "namespace_member": "createsession",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/CreateSessionRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.notebook.deletenotebook",
        "description": "Generated from `notebook` RPC `DeleteNotebook` in service `NotebookService`.",
        "operation_id": "notebook.NotebookService.DeleteNotebook",
        "method": "DELETE",
        "path": "/api/v1/notebook/delete-notebook",
        "namespace": "notebook",
        "namespace_member": "deletenotebook",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "id": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.notebook.getnotebook",
        "description": "Generated from `notebook` RPC `GetNotebook` in service `NotebookService`.",
        "operation_id": "notebook.NotebookService.GetNotebook",
        "method": "GET",
        "path": "/api/v1/notebook/get-notebook",
        "namespace": "notebook",
        "namespace_member": "getnotebook",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "id": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.notebook.listnotebooks",
        "description": "Generated from `notebook` RPC `ListNotebooks` in service `NotebookService`.",
        "operation_id": "notebook.NotebookService.ListNotebooks",
        "method": "GET",
        "path": "/api/v1/notebook/list-notebooks",
        "namespace": "notebook",
        "namespace_member": "listnotebooks",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "page": {
                      "format": "int32",
                      "type": "integer"
                    },
                    "per_page": {
                      "format": "int32",
                      "type": "integer"
                    },
                    "search": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.notebook.listsessions",
        "description": "Generated from `notebook` RPC `ListSessions` in service `KernelService`.",
        "operation_id": "notebook.KernelService.ListSessions",
        "method": "GET",
        "path": "/api/v1/notebook/list-sessions",
        "namespace": "notebook",
        "namespace_member": "listsessions",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "notebook_id": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.notebook.stopsession",
        "description": "Generated from `notebook` RPC `StopSession` in service `KernelService`.",
        "operation_id": "notebook.KernelService.StopSession",
        "method": "POST",
        "path": "/api/v1/notebook/stop-session",
        "namespace": "notebook",
        "namespace_member": "stopsession",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/StopSessionRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.notebook.updatenotebook",
        "description": "Generated from `notebook` RPC `UpdateNotebook` in service `NotebookService`.",
        "operation_id": "notebook.NotebookService.UpdateNotebook",
        "method": "PATCH",
        "path": "/api/v1/notebook/update-notebook",
        "namespace": "notebook",
        "namespace_member": "updatenotebook",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/UpdateNotebookRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.ontology.createlinktype",
        "description": "Generated from `open_foundry.ontology` RPC `CreateLinkType` in service `OntologyService`.",
        "operation_id": "open_foundry.ontology.OntologyService.CreateLinkType",
        "method": "POST",
        "path": "/api/v1/ontology/create-link-type",
        "namespace": "ontology",
        "namespace_member": "createlinktype",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/CreateLinkTypeRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.ontology.createobjecttype",
        "description": "Generated from `open_foundry.ontology` RPC `CreateObjectType` in service `OntologyService`.",
        "operation_id": "open_foundry.ontology.OntologyService.CreateObjectType",
        "method": "POST",
        "path": "/api/v1/ontology/create-object-type",
        "namespace": "ontology",
        "namespace_member": "createobjecttype",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/CreateObjectTypeRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.ontology.createproperty",
        "description": "Generated from `open_foundry.ontology` RPC `CreateProperty` in service `OntologyService`.",
        "operation_id": "open_foundry.ontology.OntologyService.CreateProperty",
        "method": "POST",
        "path": "/api/v1/ontology/create-property",
        "namespace": "ontology",
        "namespace_member": "createproperty",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/CreatePropertyRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.ontology.deletelinktype",
        "description": "Generated from `open_foundry.ontology` RPC `DeleteLinkType` in service `OntologyService`.",
        "operation_id": "open_foundry.ontology.OntologyService.DeleteLinkType",
        "method": "DELETE",
        "path": "/api/v1/ontology/delete-link-type",
        "namespace": "ontology",
        "namespace_member": "deletelinktype",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "id": {
                      "$ref": "#/components/schemas/Uuid"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.ontology.deleteobjecttype",
        "description": "Generated from `open_foundry.ontology` RPC `DeleteObjectType` in service `OntologyService`.",
        "operation_id": "open_foundry.ontology.OntologyService.DeleteObjectType",
        "method": "DELETE",
        "path": "/api/v1/ontology/delete-object-type",
        "namespace": "ontology",
        "namespace_member": "deleteobjecttype",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "id": {
                      "$ref": "#/components/schemas/Uuid"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.ontology.getobjecttype",
        "description": "Generated from `open_foundry.ontology` RPC `GetObjectType` in service `OntologyService`.",
        "operation_id": "open_foundry.ontology.OntologyService.GetObjectType",
        "method": "GET",
        "path": "/api/v1/ontology/get-object-type",
        "namespace": "ontology",
        "namespace_member": "getobjecttype",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "id": {
                      "$ref": "#/components/schemas/Uuid"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.ontology.listlinktypes",
        "description": "Generated from `open_foundry.ontology` RPC `ListLinkTypes` in service `OntologyService`.",
        "operation_id": "open_foundry.ontology.OntologyService.ListLinkTypes",
        "method": "GET",
        "path": "/api/v1/ontology/list-link-types",
        "namespace": "ontology",
        "namespace_member": "listlinktypes",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "object_type_id": {
                      "$ref": "#/components/schemas/Uuid"
                    },
                    "pagination": {
                      "$ref": "#/components/schemas/PageRequest"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.ontology.listobjecttypes",
        "description": "Generated from `open_foundry.ontology` RPC `ListObjectTypes` in service `OntologyService`.",
        "operation_id": "open_foundry.ontology.OntologyService.ListObjectTypes",
        "method": "GET",
        "path": "/api/v1/ontology/list-object-types",
        "namespace": "ontology",
        "namespace_member": "listobjecttypes",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "pagination": {
                      "$ref": "#/components/schemas/PageRequest"
                    },
                    "search": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.ontology.listproperties",
        "description": "Generated from `open_foundry.ontology` RPC `ListProperties` in service `OntologyService`.",
        "operation_id": "open_foundry.ontology.OntologyService.ListProperties",
        "method": "GET",
        "path": "/api/v1/ontology/list-properties",
        "namespace": "ontology",
        "namespace_member": "listproperties",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "object_type_id": {
                      "$ref": "#/components/schemas/Uuid"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.ontology.updateobjecttype",
        "description": "Generated from `open_foundry.ontology` RPC `UpdateObjectType` in service `OntologyService`.",
        "operation_id": "open_foundry.ontology.OntologyService.UpdateObjectType",
        "method": "PATCH",
        "path": "/api/v1/ontology/update-object-type",
        "namespace": "ontology",
        "namespace_member": "updateobjecttype",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/UpdateObjectTypeRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.pipeline.createpipeline",
        "description": "Generated from `open_foundry.pipeline` RPC `CreatePipeline` in service `PipelineService`.",
        "operation_id": "open_foundry.pipeline.PipelineService.CreatePipeline",
        "method": "POST",
        "path": "/api/v1/pipelines/create-pipeline",
        "namespace": "pipeline",
        "namespace_member": "createpipeline",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/CreatePipelineRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.pipeline.deletepipeline",
        "description": "Generated from `open_foundry.pipeline` RPC `DeletePipeline` in service `PipelineService`.",
        "operation_id": "open_foundry.pipeline.PipelineService.DeletePipeline",
        "method": "DELETE",
        "path": "/api/v1/pipelines/delete-pipeline",
        "namespace": "pipeline",
        "namespace_member": "deletepipeline",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "id": {
                      "$ref": "#/components/schemas/Uuid"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.pipeline.getdatasetlineage",
        "description": "Generated from `open_foundry.pipeline` RPC `GetDatasetLineage` in service `LineageService`.",
        "operation_id": "open_foundry.pipeline.LineageService.GetDatasetLineage",
        "method": "GET",
        "path": "/api/v1/pipelines/get-dataset-lineage",
        "namespace": "pipeline",
        "namespace_member": "getdatasetlineage",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "dataset_id": {
                      "$ref": "#/components/schemas/Uuid"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.pipeline.getfulllineage",
        "description": "Generated from `open_foundry.pipeline` RPC `GetFullLineage` in service `LineageService`.",
        "operation_id": "open_foundry.pipeline.LineageService.GetFullLineage",
        "method": "GET",
        "path": "/api/v1/pipelines/get-full-lineage",
        "namespace": "pipeline",
        "namespace_member": "getfulllineage",
        "input_schema":
            {
              "properties": {},
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.pipeline.getpipeline",
        "description": "Generated from `open_foundry.pipeline` RPC `GetPipeline` in service `PipelineService`.",
        "operation_id": "open_foundry.pipeline.PipelineService.GetPipeline",
        "method": "GET",
        "path": "/api/v1/pipelines/get-pipeline",
        "namespace": "pipeline",
        "namespace_member": "getpipeline",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "id": {
                      "$ref": "#/components/schemas/Uuid"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.pipeline.getrun",
        "description": "Generated from `open_foundry.pipeline` RPC `GetRun` in service `PipelineService`.",
        "operation_id": "open_foundry.pipeline.PipelineService.GetRun",
        "method": "GET",
        "path": "/api/v1/pipelines/get-run",
        "namespace": "pipeline",
        "namespace_member": "getrun",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "id": {
                      "$ref": "#/components/schemas/Uuid"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.pipeline.listpipelines",
        "description": "Generated from `open_foundry.pipeline` RPC `ListPipelines` in service `PipelineService`.",
        "operation_id": "open_foundry.pipeline.PipelineService.ListPipelines",
        "method": "GET",
        "path": "/api/v1/pipelines/list-pipelines",
        "namespace": "pipeline",
        "namespace_member": "listpipelines",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "pagination": {
                      "$ref": "#/components/schemas/PageRequest"
                    },
                    "search": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.pipeline.listruns",
        "description": "Generated from `open_foundry.pipeline` RPC `ListRuns` in service `PipelineService`.",
        "operation_id": "open_foundry.pipeline.PipelineService.ListRuns",
        "method": "GET",
        "path": "/api/v1/pipelines/list-runs",
        "namespace": "pipeline",
        "namespace_member": "listruns",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "pagination": {
                      "$ref": "#/components/schemas/PageRequest"
                    },
                    "pipeline_id": {
                      "$ref": "#/components/schemas/Uuid"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.pipeline.recordlineage",
        "description": "Generated from `open_foundry.pipeline` RPC `RecordLineage` in service `LineageService`.",
        "operation_id": "open_foundry.pipeline.LineageService.RecordLineage",
        "method": "POST",
        "path": "/api/v1/pipelines/record-lineage",
        "namespace": "pipeline",
        "namespace_member": "recordlineage",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/RecordLineageRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.pipeline.triggerrun",
        "description": "Generated from `open_foundry.pipeline` RPC `TriggerRun` in service `PipelineService`.",
        "operation_id": "open_foundry.pipeline.PipelineService.TriggerRun",
        "method": "POST",
        "path": "/api/v1/pipelines/trigger-run",
        "namespace": "pipeline",
        "namespace_member": "triggerrun",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/TriggerRunRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.pipeline.updatepipeline",
        "description": "Generated from `open_foundry.pipeline` RPC `UpdatePipeline` in service `PipelineService`.",
        "operation_id": "open_foundry.pipeline.PipelineService.UpdatePipeline",
        "method": "PATCH",
        "path": "/api/v1/pipelines/update-pipeline",
        "namespace": "pipeline",
        "namespace_member": "updatepipeline",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/UpdatePipelineRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.query.deletesavedquery",
        "description": "Generated from `open_foundry.query` RPC `DeleteSavedQuery` in service `QueryService`.",
        "operation_id": "open_foundry.query.QueryService.DeleteSavedQuery",
        "method": "DELETE",
        "path": "/api/v1/queries/delete-saved-query",
        "namespace": "query",
        "namespace_member": "deletesavedquery",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "id": {
                      "$ref": "#/components/schemas/Uuid"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.query.executequery",
        "description": "Generated from `open_foundry.query` RPC `ExecuteQuery` in service `QueryService`.",
        "operation_id": "open_foundry.query.QueryService.ExecuteQuery",
        "method": "POST",
        "path": "/api/v1/queries/execute-query",
        "namespace": "query",
        "namespace_member": "executequery",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/ExecuteQueryRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.query.explainquery",
        "description": "Generated from `open_foundry.query` RPC `ExplainQuery` in service `QueryService`.",
        "operation_id": "open_foundry.query.QueryService.ExplainQuery",
        "method": "POST",
        "path": "/api/v1/queries/explain-query",
        "namespace": "query",
        "namespace_member": "explainquery",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/ExplainQueryRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.query.listsavedqueries",
        "description": "Generated from `open_foundry.query` RPC `ListSavedQueries` in service `QueryService`.",
        "operation_id": "open_foundry.query.QueryService.ListSavedQueries",
        "method": "GET",
        "path": "/api/v1/queries/list-saved-queries",
        "namespace": "query",
        "namespace_member": "listsavedqueries",
        "input_schema":
            {
              "properties": {
                "query": {
                  "properties": {
                    "pagination": {
                      "$ref": "#/components/schemas/PageRequest"
                    },
                    "search": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.query.savequery",
        "description": "Generated from `open_foundry.query` RPC `SaveQuery` in service `QueryService`.",
        "operation_id": "open_foundry.query.QueryService.SaveQuery",
        "method": "POST",
        "path": "/api/v1/queries/save-query",
        "namespace": "query",
        "namespace_member": "savequery",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/SaveQueryRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v1",
        "stability": "beta",
    },
    {
        "name": "openfoundry.adminV2.getcontrolpanel",
        "description": "Curated REST overlay for `rest.admin.v2.getControlPanel`.",
        "operation_id": "rest.admin.v2.getControlPanel",
        "method": "GET",
        "path": "/api/v2/admin/control-panel",
        "namespace": "adminV2",
        "namespace_member": "getcontrolpanel",
        "input_schema":
            {
              "properties": {},
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.adminV2.updatecontrolpanel",
        "description": "Curated REST overlay for `rest.admin.v2.updateControlPanel`.",
        "operation_id": "rest.admin.v2.updateControlPanel",
        "method": "PUT",
        "path": "/api/v2/admin/control-panel",
        "namespace": "adminV2",
        "namespace_member": "updatecontrolpanel",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/UpdateControlPanelRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.adminV2.listgroups",
        "description": "Curated REST overlay for `rest.admin.v2.listGroups`.",
        "operation_id": "rest.admin.v2.listGroups",
        "method": "GET",
        "path": "/api/v2/admin/groups",
        "namespace": "adminV2",
        "namespace_member": "listgroups",
        "input_schema":
            {
              "properties": {},
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.adminV2.creategroup",
        "description": "Curated REST overlay for `rest.admin.v2.createGroup`.",
        "operation_id": "rest.admin.v2.createGroup",
        "method": "POST",
        "path": "/api/v2/admin/groups",
        "namespace": "adminV2",
        "namespace_member": "creategroup",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/CreateGroupRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.adminV2.updategroup",
        "description": "Curated REST overlay for `rest.admin.v2.updateGroup`.",
        "operation_id": "rest.admin.v2.updateGroup",
        "method": "PUT",
        "path": "/api/v2/admin/groups/{id}",
        "namespace": "adminV2",
        "namespace_member": "updategroup",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/UpdateGroupRequest"
                },
                "path": {
                  "properties": {
                    "id": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id"
                  ],
                  "type": "object"
                }
              },
              "required": [
                "body",
                "path"
              ],
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.adminV2.listpermissions",
        "description": "Curated REST overlay for `rest.admin.v2.listPermissions`.",
        "operation_id": "rest.admin.v2.listPermissions",
        "method": "GET",
        "path": "/api/v2/admin/permissions",
        "namespace": "adminV2",
        "namespace_member": "listpermissions",
        "input_schema":
            {
              "properties": {},
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.adminV2.createpermission",
        "description": "Curated REST overlay for `rest.admin.v2.createPermission`.",
        "operation_id": "rest.admin.v2.createPermission",
        "method": "POST",
        "path": "/api/v2/admin/permissions",
        "namespace": "adminV2",
        "namespace_member": "createpermission",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/CreatePermissionRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.adminV2.listpolicies",
        "description": "Curated REST overlay for `rest.admin.v2.listPolicies`.",
        "operation_id": "rest.admin.v2.listPolicies",
        "method": "GET",
        "path": "/api/v2/admin/policies",
        "namespace": "adminV2",
        "namespace_member": "listpolicies",
        "input_schema":
            {
              "properties": {},
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.adminV2.createpolicy",
        "description": "Curated REST overlay for `rest.admin.v2.createPolicy`.",
        "operation_id": "rest.admin.v2.createPolicy",
        "method": "POST",
        "path": "/api/v2/admin/policies",
        "namespace": "adminV2",
        "namespace_member": "createpolicy",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/UpsertPolicyRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.adminV2.evaluatepolicy",
        "description": "Curated REST overlay for `rest.admin.v2.evaluatePolicy`.",
        "operation_id": "rest.admin.v2.evaluatePolicy",
        "method": "POST",
        "path": "/api/v2/admin/policies/evaluate",
        "namespace": "adminV2",
        "namespace_member": "evaluatepolicy",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/EvaluatePolicyRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.adminV2.updatepolicy",
        "description": "Curated REST overlay for `rest.admin.v2.updatePolicy`.",
        "operation_id": "rest.admin.v2.updatePolicy",
        "method": "PATCH",
        "path": "/api/v2/admin/policies/{id}",
        "namespace": "adminV2",
        "namespace_member": "updatepolicy",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/UpsertPolicyRequest"
                },
                "path": {
                  "properties": {
                    "id": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id"
                  ],
                  "type": "object"
                }
              },
              "required": [
                "body",
                "path"
              ],
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.adminV2.listroles",
        "description": "Curated REST overlay for `rest.admin.v2.listRoles`.",
        "operation_id": "rest.admin.v2.listRoles",
        "method": "GET",
        "path": "/api/v2/admin/roles",
        "namespace": "adminV2",
        "namespace_member": "listroles",
        "input_schema":
            {
              "properties": {},
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.adminV2.createrole",
        "description": "Curated REST overlay for `rest.admin.v2.createRole`.",
        "operation_id": "rest.admin.v2.createRole",
        "method": "POST",
        "path": "/api/v2/admin/roles",
        "namespace": "adminV2",
        "namespace_member": "createrole",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/CreateRoleRequest"
                }
              },
              "required": [
                "body"
              ],
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.adminV2.updaterole",
        "description": "Curated REST overlay for `rest.admin.v2.updateRole`.",
        "operation_id": "rest.admin.v2.updateRole",
        "method": "PUT",
        "path": "/api/v2/admin/roles/{id}",
        "namespace": "adminV2",
        "namespace_member": "updaterole",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/UpdateRoleRequest"
                },
                "path": {
                  "properties": {
                    "id": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id"
                  ],
                  "type": "object"
                }
              },
              "required": [
                "body",
                "path"
              ],
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.adminV2.listusers",
        "description": "Curated REST overlay for `rest.admin.v2.listUsers`.",
        "operation_id": "rest.admin.v2.listUsers",
        "method": "GET",
        "path": "/api/v2/admin/users",
        "namespace": "adminV2",
        "namespace_member": "listusers",
        "input_schema":
            {
              "properties": {},
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.adminV2.getcurrentuser",
        "description": "Curated REST overlay for `rest.admin.v2.getCurrentUser`.",
        "operation_id": "rest.admin.v2.getCurrentUser",
        "method": "GET",
        "path": "/api/v2/admin/users/me",
        "namespace": "adminV2",
        "namespace_member": "getcurrentuser",
        "input_schema":
            {
              "properties": {},
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.adminV2.updateuser",
        "description": "Curated REST overlay for `rest.admin.v2.updateUser`.",
        "operation_id": "rest.admin.v2.updateUser",
        "method": "PATCH",
        "path": "/api/v2/admin/users/{id}",
        "namespace": "adminV2",
        "namespace_member": "updateuser",
        "input_schema":
            {
              "properties": {
                "body": {
                  "$ref": "#/components/schemas/UpdateUserRequest"
                },
                "path": {
                  "properties": {
                    "id": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id"
                  ],
                  "type": "object"
                }
              },
              "required": [
                "body",
                "path"
              ],
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
    {
        "name": "openfoundry.filesystemV2.getdatasetfilesystem",
        "description": "Curated REST overlay for `rest.filesystem.v2.getDatasetFilesystem`.",
        "operation_id": "rest.filesystem.v2.getDatasetFilesystem",
        "method": "GET",
        "path": "/api/v2/filesystem/datasets/{dataset_id}",
        "namespace": "filesystemV2",
        "namespace_member": "getdatasetfilesystem",
        "input_schema":
            {
              "properties": {
                "path": {
                  "properties": {
                    "dataset_id": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "dataset_id"
                  ],
                  "type": "object"
                },
                "query": {
                  "properties": {
                    "path": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              },
              "required": [
                "path"
              ],
              "type": "object"
            }
        ,
        "api_version": "v2",
        "stability": "stable",
    },
]
_MCP_TOOL_LOOKUP = {tool["name"]: tool for tool in MCP_TOOL_REGISTRY}

def list_openfoundry_mcp_tools() -> list[dict[str, Any]]:
    return MCP_TOOL_REGISTRY

def call_openfoundry_mcp_tool(
    client: OpenFoundryClient,
    tool_name: str,
    input: Mapping[str, Any] | None = None,
    headers: Mapping[str, str] | None = None,
) -> Any:
    tool = _MCP_TOOL_LOOKUP.get(tool_name)
    if tool is None:
        raise ValueError(f"Unknown OpenFoundry MCP tool: {tool_name}")
    return client.call_operation(tool["operation_id"], input=input or {}, headers=headers)

class OpenFoundryMcpAdapter:
    def __init__(self, client: OpenFoundryClient) -> None:
        self.client = client

    def list_tools(self) -> list[dict[str, Any]]:
        return list_openfoundry_mcp_tools()

    def call_tool(
        self,
        tool_name: str,
        input: Mapping[str, Any] | None = None,
        headers: Mapping[str, str] | None = None,
    ) -> Any:
        return call_openfoundry_mcp_tool(self.client, tool_name, input=input, headers=headers)