# This file is generated by `cargo run -p of-cli -- docs generate-sdk-python`.
# Do not edit manually.
from __future__ import annotations

import dataclasses
from dataclasses import dataclass
from typing import Any, get_args, get_origin

JsonValue = Any

def serialize_model(value: Any) -> Any:
    if value is None:
        return None
    if dataclasses.is_dataclass(value):
        return {field.name: serialize_model(getattr(value, field.name)) for field in dataclasses.fields(value) if getattr(value, field.name) is not None}
    if isinstance(value, list):
        return [serialize_model(item) for item in value]
    if isinstance(value, dict):
        return {key: serialize_model(item) for key, item in value.items() if item is not None}
    return value

def deserialize_model(model_type: Any, value: Any) -> Any:
    if value is None:
        return None
    origin = get_origin(model_type)
    if origin is list:
        args = get_args(model_type)
        item_type = args[0] if args else Any
        return [deserialize_model(item_type, item) for item in value]
    if origin is dict:
        args = get_args(model_type)
        value_type = args[1] if len(args) == 2 else Any
        return {str(key): deserialize_model(value_type, item) for key, item in value.items()}
    if origin is not None and str(origin).endswith('Union') or origin is getattr(__import__('types'), 'UnionType', object()):
        args = [candidate for candidate in get_args(model_type) if candidate is not type(None)]
        if len(args) == 1:
            return deserialize_model(args[0], value)
        return value
    if model_type in (Any, str, int, float, bool):
        return value
    if isinstance(model_type, type) and dataclasses.is_dataclass(model_type) and isinstance(value, dict):
        payload = {}
        for field in dataclasses.fields(model_type):
            payload[field.name] = deserialize_model(field.type, value.get(field.name))
        return model_type(**payload)
    return value

@dataclass(slots=True)
class AdminGroupsListResponse:
    count: int | None = None
    items: list[GroupResponse] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "AdminGroupsListResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class AdminPermissionsListResponse:
    count: int | None = None
    items: list[Permission] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "AdminPermissionsListResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class AdminPoliciesListResponse:
    count: int | None = None
    items: list[Policy] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "AdminPoliciesListResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class AdminRolesListResponse:
    count: int | None = None
    items: list[RoleResponse] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "AdminRolesListResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class AdminUsersListResponse:
    count: int | None = None
    items: list[UserResponse] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "AdminUsersListResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ApiError:
    code: str | None = None
    details: dict[str, Any] | None = None
    message: str | None = None
    request_id: str | None = None
    status: int | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ApiError":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class AppBrandingSettings:
    accent_color: str | None = None
    display_name: str | None = None
    favicon_url: str | None = None
    logo_url: str | None = None
    primary_color: str | None = None
    show_powered_by: bool | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "AppBrandingSettings":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class AssignRoleRequest:
    role_id: Uuid | None = None
    user_id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "AssignRoleRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class AssignRoleResponse:
    pass

@dataclass(slots=True)
class Cell:
    cell_type: str | None = None
    created_at: str | None = None
    execution_count: int | None = None
    id: str | None = None
    kernel: str | None = None
    last_output: Value | None = None
    notebook_id: str | None = None
    position: int | None = None
    source: str | None = None
    updated_at: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Cell":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class CellOutput:
    content: Value | None = None
    execution_count: int | None = None
    output_type: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CellOutput":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class Column:
    data_type: str | None = None
    name: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Column":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ColumnMeta:
    data_type: str | None = None
    name: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ColumnMeta":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class Connection:
    config: dict[str, str] | None = None
    connector_type: ConnectorType | None = None
    created_at: str | None = None
    id: Uuid | None = None
    last_sync_at: str | None = None
    name: str | None = None
    status: ConnectionStatus | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Connection":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ControlPanelSettings:
    allow_self_signup: bool | None = None
    allowed_email_domains: list[str] | None = None
    announcement_banner: str | None = None
    default_app_branding: AppBrandingSettings | None = None
    default_region: str | None = None
    deployment_mode: str | None = None
    docs_url: str | None = None
    maintenance_mode: bool | None = None
    platform_name: str | None = None
    release_channel: str | None = None
    restricted_operations: list[str] | None = None
    status_page_url: str | None = None
    support_email: str | None = None
    updated_at: str | None = None
    updated_by: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ControlPanelSettings":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class CreateCellRequest:
    cell_type: str | None = None
    kernel: str | None = None
    notebook_id: str | None = None
    position: int | None = None
    source: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CreateCellRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class CreateConnectionRequest:
    config: dict[str, str] | None = None
    connector_type: ConnectorType | None = None
    name: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CreateConnectionRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class CreateDatasetRequest:
    description: str | None = None
    format: DatasetFormat | None = None
    name: str | None = None
    tags: list[str] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CreateDatasetRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class CreateGroupRequest:
    description: str | None = None
    name: str | None = None
    role_ids: list[str] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CreateGroupRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class CreateLinkTypeRequest:
    cardinality: str | None = None
    description: str | None = None
    display_name: str | None = None
    name: str | None = None
    source_type_id: Uuid | None = None
    target_type_id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CreateLinkTypeRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class CreateNotebookRequest:
    default_kernel: str | None = None
    description: str | None = None
    name: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CreateNotebookRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class CreateObjectTypeRequest:
    color: str | None = None
    description: str | None = None
    display_name: str | None = None
    icon: str | None = None
    name: str | None = None
    primary_key_property: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CreateObjectTypeRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class CreatePermissionRequest:
    action: str | None = None
    description: str | None = None
    resource: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CreatePermissionRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class CreatePipelineRequest:
    description: str | None = None
    name: str | None = None
    nodes: list[PipelineNode] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CreatePipelineRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class CreatePropertyRequest:
    default_value_json: str | None = None
    description: str | None = None
    display_name: str | None = None
    name: str | None = None
    object_type_id: Uuid | None = None
    property_type: str | None = None
    required: bool | None = None
    unique_constraint: bool | None = None
    validation_rules_json: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CreatePropertyRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class CreateRoleRequest:
    description: str | None = None
    name: str | None = None
    permission_ids: list[str] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CreateRoleRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class CreateSessionRequest:
    kernel: str | None = None
    notebook_id: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CreateSessionRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class Dataset:
    created_at: str | None = None
    current_version: int | None = None
    description: str | None = None
    format: DatasetFormat | None = None
    id: Uuid | None = None
    name: str | None = None
    owner_id: Uuid | None = None
    row_count: int | None = None
    schema: Schema | None = None
    size_bytes: int | None = None
    storage_path: str | None = None
    tags: list[str] | None = None
    updated_at: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Dataset":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class DatasetVersion:
    created_at: str | None = None
    message: str | None = None
    row_count: int | None = None
    size_bytes: int | None = None
    version: int | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DatasetVersion":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class DeleteConnectionRequest:
    id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DeleteConnectionRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class DeleteConnectionResponse:
    pass

@dataclass(slots=True)
class DeleteDatasetRequest:
    id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DeleteDatasetRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class DeleteDatasetResponse:
    pass

@dataclass(slots=True)
class DeleteLinkTypeRequest:
    id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DeleteLinkTypeRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class DeleteLinkTypeResponse:
    pass

@dataclass(slots=True)
class DeleteNotebookRequest:
    id: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DeleteNotebookRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class DeleteObjectTypeRequest:
    id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DeleteObjectTypeRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class DeleteObjectTypeResponse:
    pass

@dataclass(slots=True)
class DeletePipelineRequest:
    id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DeletePipelineRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class DeletePipelineResponse:
    pass

@dataclass(slots=True)
class DeleteSavedQueryRequest:
    id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DeleteSavedQueryRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class DeleteSavedQueryResponse:
    pass

@dataclass(slots=True)
class ErrorDetail:
    code: str | None = None
    message: str | None = None
    metadata: dict[str, str] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ErrorDetail":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class EvaluatePolicyRequest:
    action: str | None = None
    resource: str | None = None
    resource_attributes: dict[str, Any] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "EvaluatePolicyRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ExecuteCellRequest:
    cell_id: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ExecuteCellRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ExecuteQueryRequest:
    limit: int | None = None
    offset: int | None = None
    parameters: dict[str, str] | None = None
    sql: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ExecuteQueryRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ExplainQueryRequest:
    sql: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ExplainQueryRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ExplainQueryResponse:
    logical_plan: str | None = None
    physical_plan: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ExplainQueryResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class Field:
    field_type: FieldType | None = None
    metadata: dict[str, str] | None = None
    name: str | None = None
    nullable: bool | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Field":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class FilesystemBreadcrumb:
    name: str | None = None
    path: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "FilesystemBreadcrumb":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class FilesystemEntry:
    content_type: str | None = None
    entry_type: str | None = None
    last_modified: str | None = None
    metadata: dict[str, Any] | None = None
    name: str | None = None
    path: str | None = None
    size_bytes: int | None = None
    storage_path: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "FilesystemEntry":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class FilesystemListResponse:
    active_branch: str | None = None
    breadcrumbs: list[FilesystemBreadcrumb] | None = None
    current_version: int | None = None
    dataset_id: str | None = None
    entries: list[FilesystemEntry] | None = None
    items: list[FilesystemEntry] | None = None
    requested_path: str | None = None
    root: str | None = None
    sections: FilesystemSections | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "FilesystemListResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class FilesystemSections:
    branches: int | None = None
    versions: int | None = None
    views: int | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "FilesystemSections":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class GetDatasetLineageRequest:
    dataset_id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "GetDatasetLineageRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class GetDatasetRequest:
    id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "GetDatasetRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class GetFullLineageRequest:
    pass

@dataclass(slots=True)
class GetMeRequest:
    pass

@dataclass(slots=True)
class GetNotebookRequest:
    id: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "GetNotebookRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class GetObjectTypeRequest:
    id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "GetObjectTypeRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class GetPipelineRequest:
    id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "GetPipelineRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class GetRunRequest:
    id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "GetRunRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class GetVersionsRequest:
    dataset_id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "GetVersionsRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class GetVersionsResponse:
    versions: list[DatasetVersion] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "GetVersionsResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class GroupResponse:
    created_at: str | None = None
    description: str | None = None
    id: str | None = None
    member_count: int | None = None
    name: str | None = None
    role_ids: list[str] | None = None
    roles: list[str] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "GroupResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class HealthCheckRequest:
    service: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "HealthCheckRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class HealthCheckResponse:
    pass

@dataclass(slots=True)
class InferSchemaRequest:
    connection_id: Uuid | None = None
    table_name: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "InferSchemaRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class InferSchemaResponse:
    columns: list[InferredColumn] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "InferSchemaResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class InferredColumn:
    inferred_type: str | None = None
    name: str | None = None
    nullable: bool | None = None
    source_type: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "InferredColumn":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class LineageEdge:
    node_id: str | None = None
    pipeline_id: Uuid | None = None
    source_dataset_id: Uuid | None = None
    target_dataset_id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "LineageEdge":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class LineageGraph:
    edges: list[LineageEdge] | None = None
    nodes: list[LineageNode] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "LineageGraph":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class LineageNode:
    dataset_id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "LineageNode":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class LinkType:
    cardinality: str | None = None
    created_at: str | None = None
    description: str | None = None
    display_name: str | None = None
    id: Uuid | None = None
    name: str | None = None
    owner_id: Uuid | None = None
    source_type_id: Uuid | None = None
    target_type_id: Uuid | None = None
    updated_at: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "LinkType":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListConnectionsRequest:
    pagination: PageRequest | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListConnectionsRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListConnectionsResponse:
    connections: list[Connection] | None = None
    pagination: PageResponse | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListConnectionsResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListDatasetsRequest:
    pagination: PageRequest | None = None
    search: str | None = None
    tags: list[str] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListDatasetsRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListDatasetsResponse:
    datasets: list[Dataset] | None = None
    pagination: PageResponse | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListDatasetsResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListLinkTypesRequest:
    object_type_id: Uuid | None = None
    pagination: PageRequest | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListLinkTypesRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListLinkTypesResponse:
    link_types: list[LinkType] | None = None
    pagination: PageResponse | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListLinkTypesResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListNotebooksRequest:
    page: int | None = None
    per_page: int | None = None
    search: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListNotebooksRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListNotebooksResponse:
    data: list[Notebook] | None = None
    page: int | None = None
    per_page: int | None = None
    total: int | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListNotebooksResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListObjectTypesRequest:
    pagination: PageRequest | None = None
    search: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListObjectTypesRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListObjectTypesResponse:
    object_types: list[ObjectType] | None = None
    pagination: PageResponse | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListObjectTypesResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListPipelinesRequest:
    pagination: PageRequest | None = None
    search: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListPipelinesRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListPipelinesResponse:
    pagination: PageResponse | None = None
    pipelines: list[Pipeline] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListPipelinesResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListPropertiesRequest:
    object_type_id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListPropertiesRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListPropertiesResponse:
    properties: list[Property] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListPropertiesResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListRolesRequest:
    pass

@dataclass(slots=True)
class ListRolesResponse:
    roles: list[Role] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListRolesResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListRunsRequest:
    pagination: PageRequest | None = None
    pipeline_id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListRunsRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListRunsResponse:
    pagination: PageResponse | None = None
    runs: list[PipelineRun] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListRunsResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListSavedQueriesRequest:
    pagination: PageRequest | None = None
    search: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListSavedQueriesRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListSavedQueriesResponse:
    pagination: PageResponse | None = None
    queries: list[SavedQuery] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListSavedQueriesResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListSessionsRequest:
    notebook_id: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListSessionsRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ListSessionsResponse:
    data: list[Session] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListSessionsResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class LoginRequest:
    email: str | None = None
    password: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "LoginRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class Notebook:
    created_at: str | None = None
    default_kernel: str | None = None
    description: str | None = None
    id: str | None = None
    name: str | None = None
    owner_id: str | None = None
    updated_at: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Notebook":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class ObjectType:
    color: str | None = None
    created_at: str | None = None
    description: str | None = None
    display_name: str | None = None
    icon: str | None = None
    id: Uuid | None = None
    name: str | None = None
    owner_id: Uuid | None = None
    primary_key_property: str | None = None
    updated_at: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ObjectType":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class PageRequest:
    page: int | None = None
    per_page: int | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "PageRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class PageResponse:
    page: int | None = None
    per_page: int | None = None
    total: int | None = None
    total_pages: int | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "PageResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class Permission:
    action: str | None = None
    created_at: str | None = None
    description: str | None = None
    id: str | None = None
    resource: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Permission":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class Pipeline:
    created_at: str | None = None
    description: str | None = None
    id: Uuid | None = None
    name: str | None = None
    nodes: list[PipelineNode] | None = None
    owner_id: Uuid | None = None
    status: str | None = None
    updated_at: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Pipeline":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class PipelineNode:
    config_json: str | None = None
    depends_on: list[str] | None = None
    id: str | None = None
    input_dataset_ids: list[Uuid] | None = None
    label: str | None = None
    output_dataset_id: Uuid | None = None
    transform_type: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "PipelineNode":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class PipelineRun:
    error_message: str | None = None
    finished_at: str | None = None
    id: Uuid | None = None
    node_results_json: str | None = None
    pipeline_id: Uuid | None = None
    started_at: str | None = None
    started_by: Uuid | None = None
    status: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "PipelineRun":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class Policy:
    action: str | None = None
    conditions: dict[str, Any] | None = None
    created_at: str | None = None
    created_by: str | None = None
    description: str | None = None
    effect: str | None = None
    enabled: bool | None = None
    id: str | None = None
    name: str | None = None
    resource: str | None = None
    row_filter: str | None = None
    updated_at: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Policy":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class PolicyEvaluationResult:
    allowed: bool | None = None
    deny_policy_ids: list[str] | None = None
    matched_policy_ids: list[str] | None = None
    row_filter: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "PolicyEvaluationResult":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class PreviewDataRequest:
    dataset_id: Uuid | None = None
    limit: int | None = None
    offset: int | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "PreviewDataRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class PreviewDataResponse:
    columns: list[Column] | None = None
    rows: list[Row] | None = None
    total_rows: int | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "PreviewDataResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class Property:
    created_at: str | None = None
    default_value_json: str | None = None
    description: str | None = None
    display_name: str | None = None
    id: Uuid | None = None
    name: str | None = None
    object_type_id: Uuid | None = None
    property_type: str | None = None
    required: bool | None = None
    unique_constraint: bool | None = None
    updated_at: str | None = None
    validation_rules_json: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Property":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class QueryResult:
    columns: list[ColumnMeta] | None = None
    execution_time_ms: int | None = None
    rows: list[RowData] | None = None
    rows_scanned: int | None = None
    total_rows: int | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "QueryResult":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class RecordLineageRequest:
    node_id: str | None = None
    pipeline_id: Uuid | None = None
    source_dataset_id: Uuid | None = None
    target_dataset_id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "RecordLineageRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class RecordLineageResponse:
    pass

@dataclass(slots=True)
class RefreshRequest:
    refresh_token: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "RefreshRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class RegisterRequest:
    email: str | None = None
    name: str | None = None
    password: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "RegisterRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class RegisterResponse:
    user_id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "RegisterResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class Role:
    description: str | None = None
    id: Uuid | None = None
    name: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Role":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class RoleResponse:
    created_at: str | None = None
    description: str | None = None
    id: str | None = None
    name: str | None = None
    permission_ids: list[str] | None = None
    permissions: list[str] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "RoleResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class Row:
    values: dict[str, str] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Row":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class RowData:
    values: list[str] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "RowData":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class SaveQueryRequest:
    description: str | None = None
    name: str | None = None
    sql: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SaveQueryRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class SavedQuery:
    created_at: str | None = None
    description: str | None = None
    id: Uuid | None = None
    name: str | None = None
    owner_id: Uuid | None = None
    sql: str | None = None
    updated_at: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SavedQuery":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class Schema:
    fields: list[Field] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Schema":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class Session:
    created_at: str | None = None
    id: str | None = None
    kernel: str | None = None
    last_activity: str | None = None
    notebook_id: str | None = None
    started_by: str | None = None
    status: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Session":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class StopSessionRequest:
    session_id: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "StopSessionRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class SyncConnectionRequest:
    connection_id: Uuid | None = None
    table_name: str | None = None
    target_dataset_id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SyncConnectionRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class SyncStatus:
    error: str | None = None
    rows_synced: int | None = None
    status: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SyncStatus":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class TestConnectionRequest:
    id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "TestConnectionRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class TestConnectionResponse:
    message: str | None = None
    success: bool | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "TestConnectionResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class Timestamps:
    created_at: str | None = None
    updated_at: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Timestamps":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class TokenPair:
    access_token: str | None = None
    expires_in: int | None = None
    refresh_token: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "TokenPair":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class TriggerRunRequest:
    pipeline_id: Uuid | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "TriggerRunRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class UpdateCellRequest:
    cell_id: str | None = None
    cell_type: str | None = None
    kernel: str | None = None
    position: int | None = None
    source: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "UpdateCellRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class UpdateControlPanelRequest:
    allow_self_signup: bool | None = None
    allowed_email_domains: list[str] | None = None
    announcement_banner: str | None = None
    default_app_branding: AppBrandingSettings | None = None
    default_region: str | None = None
    deployment_mode: str | None = None
    docs_url: str | None = None
    maintenance_mode: bool | None = None
    platform_name: str | None = None
    release_channel: str | None = None
    restricted_operations: list[str] | None = None
    status_page_url: str | None = None
    support_email: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "UpdateControlPanelRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class UpdateDatasetRequest:
    description: str | None = None
    id: Uuid | None = None
    name: str | None = None
    tags: list[str] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "UpdateDatasetRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class UpdateGroupRequest:
    description: str | None = None
    role_ids: list[str] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "UpdateGroupRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class UpdateNotebookRequest:
    default_kernel: str | None = None
    description: str | None = None
    id: str | None = None
    name: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "UpdateNotebookRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class UpdateObjectTypeRequest:
    color: str | None = None
    description: str | None = None
    display_name: str | None = None
    icon: str | None = None
    id: Uuid | None = None
    primary_key_property: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "UpdateObjectTypeRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class UpdatePipelineRequest:
    description: str | None = None
    id: Uuid | None = None
    name: str | None = None
    nodes: list[PipelineNode] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "UpdatePipelineRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class UpdateRoleRequest:
    description: str | None = None
    permission_ids: list[str] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "UpdateRoleRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class UpdateUserRequest:
    attributes: dict[str, Any] | None = None
    is_active: bool | None = None
    mfa_enforced: bool | None = None
    name: str | None = None
    organization_id: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "UpdateUserRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class UpsertPolicyRequest:
    action: str | None = None
    conditions: dict[str, Any] | None = None
    description: str | None = None
    effect: str | None = None
    enabled: bool | None = None
    name: str | None = None
    resource: str | None = None
    row_filter: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "UpsertPolicyRequest":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class UserInfo:
    email: str | None = None
    id: Uuid | None = None
    name: str | None = None
    roles: list[str] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "UserInfo":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class UserResponse:
    attributes: dict[str, Any] | None = None
    auth_source: str | None = None
    created_at: str | None = None
    email: str | None = None
    groups: list[str] | None = None
    id: str | None = None
    is_active: bool | None = None
    mfa_enabled: bool | None = None
    mfa_enforced: bool | None = None
    name: str | None = None
    organization_id: str | None = None
    permissions: list[str] | None = None
    roles: list[str] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "UserResponse":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

@dataclass(slots=True)
class Uuid:
    value: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Uuid":
        return deserialize_model(cls, data)

    def to_dict(self) -> dict[str, Any]:
        return serialize_model(self)

ConnectionStatus = str

ConnectorType = str

DatasetFormat = str

FieldType = str

Value = Any
