package ts

// Templates are kept as raw strings (not embed.FS) so the unit tests
// stay hermetic and the byte-deterministic snapshot tests don't need a
// filesystem fixture in the repo. text/template is the only
// dependency — no go.mod changes.

const tmplPackageJSON = `{
  "name": "@openfoundry-sdk/{{.TenantSlug}}",
  "version": "{{.PackageVersion}}",
  "description": "OpenFoundry generated typed client for ontology {{.OntologyVersion}} (tenant {{.TenantID}}).",
  "type": "module",
  "main": "index.ts",
  "types": "index.ts",
  "files": [
    "index.ts",
    "types.ts",
    "actions.ts",
    "client.ts",
    "package.json",
    "tsconfig.json"
  ],
  "dependencies": {},
  "openfoundry": {
    "ontologyVersion": "{{.OntologyVersion}}",
    "tenantId": "{{.TenantID}}",
    "target": "ts"
  }
}
`

const tmplTSConfig = `{
  "compilerOptions": {
    "target": "es2022",
    "module": "esnext",
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "declaration": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["index.ts", "types.ts", "actions.ts", "client.ts"]
}
`

const tmplIndex = `// Generated by OpenFoundry sdk-generation-service.
// Ontology version: {{.OntologyVersion}}
// Tenant: {{.TenantID}}
export * from "./types";
export * from "./actions";
export * from "./client";
`

const tmplTypes = `// Generated by OpenFoundry sdk-generation-service.
// Ontology version: {{.OntologyVersion}}

{{range .ObjectTypes -}}
export interface {{.TSName}} {
{{- range .Properties}}
  {{if .Optional}}{{.Name}}?: {{.TSType}}{{else}}{{.Name}}: {{.TSType}}{{end}};
{{- end}}
}

{{end -}}
{{if .LinkTypes -}}
// Link relationships pinned at generation time for client-side helpers.
export interface OntologyLinks {
{{- range .LinkTypes}}
  readonly {{.Name}}: {
    readonly source: "{{.Source}}";
    readonly target: "{{.Target}}";
    readonly cardinality: "{{.Cardinality}}";
  };
{{- end}}
}
{{end -}}
`

const tmplActions = `// Generated by OpenFoundry sdk-generation-service.
// Ontology version: {{.OntologyVersion}}

{{range .ActionTypes -}}
export interface {{.TSName}}Params {
{{- range .Parameters}}
  {{if .Optional}}{{.Name}}?: {{.TSType}}{{else}}{{.Name}}: {{.TSType}}{{end}};
{{- end}}
}

export interface {{.TSName}}Result {
  readonly applied: true;
  readonly actionName: "{{.APIName}}";
}

{{end -}}
`

const tmplClient = `// Generated by OpenFoundry sdk-generation-service.
// Ontology version: {{.OntologyVersion}}
import type {
{{- range .ObjectTypes}}
  {{.TSName}},
{{- end}}
{{- range .ActionTypes}}
  {{.TSName}}Params,
  {{.TSName}}Result,
{{- end}}
} from "./types";
{{if .ActionTypes -}}
import type {
{{- range .ActionTypes}}
  {{.TSName}}Params as _{{.TSName}}Params,
  {{.TSName}}Result as _{{.TSName}}Result,
{{- end}}
} from "./actions";
{{- end}}

export interface OSDKClientOptions {
  readonly baseURL: string;
  readonly getToken: () => string | Promise<string>;
}

export class OSDKClient {
  constructor(private readonly options: OSDKClientOptions) {}

  readonly objects = {
{{- range .ObjectTypes}}
    {{.TSField}}: {
      list: async (): Promise<{{.TSName}}[]> => {
        return this.request<{{.TSName}}[]>("GET", "/api/v1/ontology/objects/{{.APIName}}");
      },
      get: async (id: string): Promise<{{.TSName}} | null> => {
        return this.request<{{.TSName}} | null>("GET", "/api/v1/ontology/objects/{{.APIName}}/" + encodeURIComponent(id));
      },
    },
{{- end}}
  } as const;

{{if .ActionTypes -}}
  readonly actions = {
{{- range .ActionTypes}}
    {{.TSField}}: async (params: _{{.TSName}}Params): Promise<_{{.TSName}}Result> => {
      return this.request<_{{.TSName}}Result>("POST", "/api/v1/ontology/actions/{{.APIName}}", params);
    },
{{- end}}
  } as const;
{{- end}}

  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const token = await this.options.getToken();
    const headers: Record<string, string> = {
      Accept: "application/json",
    };
    if (token) {
      headers.Authorization = "Bearer " + token;
    }
    if (body !== undefined) {
      headers["Content-Type"] = "application/json";
    }
    const response = await fetch(this.options.baseURL.replace(/\/$/, "") + path, {
      method,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    if (!response.ok) {
      const text = await response.text().catch(() => "");
      throw new Error("OSDK request failed: " + response.status + " " + response.statusText + " " + text);
    }
    return (await response.json()) as T;
  }
}
`
