// Package authmw is OpenFoundry's shared HTTP auth middleware.
//
// What this package owns:
//
//   - [Claims] / [SessionScope] wire-stable across services and SDKs.
//   - [JWTConfig] with HS256 + RS256 signing/verification, env-driven
//     [JWTConfig.WithEnvDefaults], and unattended secret resolution
//     ([LoadOrGenerate], [ResolveUnattended]).
//   - Token factory helpers ([BuildAccessClaims], [BuildRefreshClaims],
//     [BuildAPIKeyClaims], plus the *WithScope variants).
//   - HTTP middleware: [Middleware] (bearer extraction + JWT
//     validation + context injection) and [Required].
//   - RBAC middleware: [RequireRoles], [RequireAdmin],
//     [RequirePermissions] plus the well-known role constants.
//   - Marking enforcement: [CallerClearances],
//     [MarkingNameResolver], [StaticMarkingNameResolver],
//     [EnforceMarkings] backed by core-models/security.MarkingID.
//   - Row-level-security primitives: [RLSContext] and the
//     [RLSContext.OrgFilter] / [RLSContext.OwnerOrOrgFilter] SQL
//     fragment helpers.
//   - Tenant resolution: [TenantContext] / [TenantContextFromClaims]
//     with standard / team / enterprise quota tiers.
//   - Functional options for the decoder + middleware:
//     [WithAllowedTokenUses], [WithAnyTokenUse] (see options.go).
//   - Prometheus counters: auth_invalid_token_total{reason} and
//     auth_secret_autogenerated_total{path}. Register them on a
//     service Registry via [RegisterMetrics] from
//     `cmd/<service>/main.go`.
//
// # token_use filter
//
// [DecodeToken] enforces a `token_use` allowlist. With no options the
// default is []string{"access"} so non-access tokens
// ("mfa_challenge", "refresh", "api_key", debug-issued JWTs, …) cannot
// authenticate a normal /api/v1 request — closing the "permissions
// and roles are empty so it can't do anything" implicit gap that
// fronted the MFA challenge token until 2026-05.
//
// # Unattended secret autogeneration — dev only
//
// [LoadOrGenerate] / [ResolveUnattended] will create an HS256 secret
// on first boot and persist it under the supplied path. This is
// designed for `docker compose up` and local k3s scenarios where no
// secret manager is wired. It MUST NOT be used in production
// containers without a persistent volume mounted at the secret path:
// every restart regenerates the secret and silently invalidates every
// token issued before the restart. Operators receive a slog.Error
// log and the auth_secret_autogenerated_total{path} counter
// increments — alert on this in any non-dev environment.
//
// # Known follow-ups (not addressed in this package)
//
//   - services/identity-federation-service/internal/service/challenge.go
//     ::ValidateMFAChallenge calls [DecodeToken] with no options, so
//     the new default ("access") will reject the mfa_challenge token
//     it deliberately consumes. Migrate that callsite to
//     `DecodeToken(jwt, token, WithAllowedTokenUses("mfa_challenge"))`
//     and add a matching test. Tracked separately to keep this
//     change scoped to libs/auth-middleware.
package authmw
