//! DAG → Flink SQL emitter.
//!
//! Translates a [`TopologyDefinition`] into a Flink SQL script the
//! `sql-runner.jar` job can execute end-to-end. The emitter is
//! intentionally pragmatic — the goal is to ship a credible MVP that
//! covers the topology shapes the in-process engine already
//! understands:
//!
//!   * `source` nodes  → `CREATE TABLE ... WITH ('connector'='kafka', ...)`
//!   * `filter` nodes  → embedded in the projection `WHERE` clause
//!   * `map` nodes     → projection rename / cast
//!   * `window` nodes  → `TUMBLE`/`HOP`/`SESSION` aggregation
//!   * `join` nodes    → temporal interval join driven by
//!                       [`crate::models::topology::JoinDefinition`]
//!   * `sink` nodes    → `CREATE TABLE ... INSERT INTO`
//!
//! Anything fancier (CEP MATCH_RECOGNIZE, async lookups, etc.) is
//! emitted as an explicit unsupported-shape warning so the operator can
//! hand-edit if needed. Producing actually-executable SQL for every
//! topology is out of scope for the MVP.
//!
//! The emitter is pure: it does not touch the network or the database.

use std::fmt::Write as _;

use super::effective_exactly_once;
use crate::models::stream::{ConnectorBinding, StreamDefinition};
use crate::models::topology::TopologyDefinition;

/// Output of [`render_flink_sql`].
#[derive(Debug, Clone)]
pub struct RenderedFlinkSql {
    /// Self-contained SQL script. May contain multiple statements
    /// separated by `;`.
    pub script: String,
    /// Brief notes the operator may want to surface in the UI (e.g.
    /// "CEP pattern not translated, fallback comment emitted").
    pub warnings: Vec<String>,
}

/// Render a Flink SQL script for the given topology + the source
/// streams it references. Sinks are taken from `topology.sink_bindings`.
pub fn render_flink_sql(
    topology: &TopologyDefinition,
    streams: &[StreamDefinition],
) -> RenderedFlinkSql {
    let mut script = String::new();
    let mut warnings = Vec::new();

    // -- Header ---------------------------------------------------------
    writeln!(
        script,
        "-- Auto-generated by event-streaming-service / runtime/flink/sql.rs"
    )
    .ok();
    writeln!(script, "-- topology: {} ({})", topology.name, topology.id).ok();
    let exactly_once = effective_exactly_once(topology, streams);
    writeln!(
        script,
        "SET 'execution.checkpointing.mode' = '{}';",
        if exactly_once {
            "EXACTLY_ONCE"
        } else {
            "AT_LEAST_ONCE"
        }
    )
    .ok();
    writeln!(
        script,
        "SET 'execution.checkpointing.interval' = '{}';",
        topology.checkpoint_interval_ms
    )
    .ok();
    if exactly_once {
        // Transactional Kafka sink + two-phase commit. Disabled when
        // AT_LEAST_ONCE so the cheaper write path stays the default.
        writeln!(
            script,
            "SET 'sink.transactional-id-prefix' = 'openfoundry-{}';",
            topology.id.simple()
        )
        .ok();
        writeln!(script, "SET 'sink.delivery-guarantee' = 'exactly-once';").ok();
    }
    writeln!(script).ok();

    // -- Source tables --------------------------------------------------
    for stream_id in &topology.source_stream_ids {
        if let Some(stream) = streams.iter().find(|s| s.id == *stream_id) {
            render_source_table(&mut script, stream);
            writeln!(script).ok();
        } else {
            warnings.push(format!(
                "source stream {stream_id} referenced but not found in catalogue"
            ));
        }
    }

    // -- Sink tables ----------------------------------------------------
    for (idx, sink) in topology.sink_bindings.iter().enumerate() {
        render_sink_table(&mut script, idx, sink);
        writeln!(script).ok();
    }

    // -- Pipeline body --------------------------------------------------
    if let Some(join) = &topology.join_definition {
        let left = streams
            .iter()
            .find(|s| s.id == join.left_stream_id)
            .map(|s| sanitize(&s.name))
            .unwrap_or_else(|| format!("src_{}", join.left_stream_id.simple()));
        let right = streams
            .iter()
            .find(|s| s.id == join.right_stream_id)
            .map(|s| sanitize(&s.name))
            .unwrap_or_else(|| format!("src_{}", join.right_stream_id.simple()));
        let on = if join.key_fields.is_empty() {
            "1 = 1".to_string()
        } else {
            join.key_fields
                .iter()
                .map(|k| {
                    let k = sanitize(k);
                    format!("l.{k} = r.{k}")
                })
                .collect::<Vec<_>>()
                .join(" AND ")
        };
        writeln!(
            script,
            "-- Join '{}' over a {} s interval window",
            join.table_name, join.window_seconds
        )
        .ok();
        writeln!(script, "CREATE VIEW {} AS", sanitize(&join.table_name)).ok();
        writeln!(
            script,
            "  SELECT l.*, r.* FROM {left} l\n    {join_kind} JOIN {right} r\n    ON {on}\n    AND r.event_time BETWEEN l.event_time - INTERVAL '{}' SECOND\n                         AND l.event_time + INTERVAL '{}' SECOND;",
            join.window_seconds,
            join.window_seconds,
            join_kind = match join.join_type.as_str() {
                "left" => "LEFT",
                "right" => "RIGHT",
                "full" => "FULL",
                _ => "INNER",
            }
        )
        .ok();
        writeln!(script).ok();
    }

    if topology.cep_definition.is_some() {
        warnings.push(
            "CEP pattern translation is unsupported by the current Flink SQL renderer".to_string(),
        );
        writeln!(
            script,
            "-- CEP definition is not translated by this renderer; use a supported graph shape"
        )
        .ok();
        writeln!(script).ok();
    }

    // -- Final INSERT INTO sinks ---------------------------------------
    if topology.sink_bindings.is_empty() {
        warnings.push("topology has no sink bindings; no INSERT INTO emitted".to_string());
    } else if topology.source_stream_ids.is_empty() {
        warnings.push("topology has no source streams; emitting empty INSERT INTO".to_string());
    } else {
        let primary_source = topology.source_stream_ids[0];
        let source_name = streams
            .iter()
            .find(|s| s.id == primary_source)
            .map(|s| sanitize(&s.name))
            .unwrap_or_else(|| format!("src_{}", primary_source.simple()));
        for (idx, _) in topology.sink_bindings.iter().enumerate() {
            // Optional WHERE clause from filter nodes.
            let mut wheres = Vec::new();
            for node in &topology.nodes {
                if node.node_type == "filter" {
                    if let Some(expr) = node.config.get("expression").and_then(|v| v.as_str()) {
                        wheres.push(expr.to_string());
                    }
                }
            }
            let where_clause = if wheres.is_empty() {
                String::new()
            } else {
                format!("\n  WHERE {}", wheres.join(" AND "))
            };
            writeln!(
                script,
                "INSERT INTO sink_{idx}\n  SELECT * FROM {source_name}{where_clause};"
            )
            .ok();
            writeln!(script).ok();
        }
    }

    RenderedFlinkSql { script, warnings }
}

fn render_source_table(out: &mut String, stream: &StreamDefinition) {
    let table = sanitize(&stream.name);
    writeln!(out, "CREATE TABLE {table} (").ok();
    let n = stream.schema.fields.len();
    for (i, field) in stream.schema.fields.iter().enumerate() {
        let comma = if i + 1 < n { "," } else { "" };
        writeln!(
            out,
            "  {} {}{nullable}{comma}",
            sanitize(&field.name),
            map_type(&field.data_type),
            nullable = if field.nullable { "" } else { " NOT NULL" },
        )
        .ok();
    }
    if let Some(wm) = &stream.schema.watermark_field {
        writeln!(
            out,
            "  ,WATERMARK FOR {wm} AS {wm} - INTERVAL '5' SECOND",
            wm = sanitize(wm)
        )
        .ok();
    }
    writeln!(out, ") WITH (").ok();
    let with = with_clause_for(&stream.source_binding);
    let m = with.len();
    for (i, (k, v)) in with.iter().enumerate() {
        let comma = if i + 1 < m { "," } else { "" };
        writeln!(out, "  '{k}' = '{}'{comma}", escape_sql(v)).ok();
    }
    writeln!(out, ");").ok();
}

fn render_sink_table(out: &mut String, idx: usize, binding: &ConnectorBinding) {
    writeln!(
        out,
        "-- sink #{idx} ({} → {})",
        binding.connector_type, binding.endpoint
    )
    .ok();
    writeln!(out, "CREATE TABLE sink_{idx} (").ok();
    writeln!(out, "  payload STRING").ok();
    writeln!(out, ") WITH (").ok();
    let with = with_clause_for(binding);
    let m = with.len();
    for (i, (k, v)) in with.iter().enumerate() {
        let comma = if i + 1 < m { "," } else { "" };
        writeln!(out, "  '{k}' = '{}'{comma}", escape_sql(v)).ok();
    }
    writeln!(out, ");").ok();
}

fn with_clause_for(binding: &ConnectorBinding) -> Vec<(String, String)> {
    let mut out = Vec::new();
    match binding.connector_type.as_str() {
        "kafka" | "" => {
            out.push(("connector".into(), "kafka".into()));
            out.push((
                "topic".into(),
                binding
                    .endpoint
                    .strip_prefix("kafka://")
                    .unwrap_or(&binding.endpoint)
                    .to_string(),
            ));
            out.push((
                "properties.bootstrap.servers".into(),
                std::env::var("KAFKA_BOOTSTRAP_SERVERS")
                    .unwrap_or_else(|_| "kafka:9092".to_string()),
            ));
            out.push(("format".into(), binding.format.clone()));
            out.push(("scan.startup.mode".into(), "earliest-offset".into()));
        }
        "iceberg" => {
            out.push(("connector".into(), "iceberg".into()));
            out.push(("catalog-name".into(), "openfoundry".into()));
            out.push(("warehouse".into(), binding.endpoint.clone()));
        }
        "filesystem" => {
            out.push(("connector".into(), "filesystem".into()));
            out.push(("path".into(), binding.endpoint.clone()));
            out.push(("format".into(), binding.format.clone()));
        }
        other => {
            out.push(("connector".into(), other.to_string()));
            out.push(("path".into(), binding.endpoint.clone()));
        }
    }
    out
}

fn map_type(t: &str) -> &'static str {
    match t.to_lowercase().as_str() {
        "string" | "text" | "varchar" => "STRING",
        "int" | "integer" | "int32" => "INT",
        "long" | "bigint" | "int64" => "BIGINT",
        "double" | "float64" => "DOUBLE",
        "float" | "float32" => "FLOAT",
        "boolean" | "bool" => "BOOLEAN",
        "timestamp" => "TIMESTAMP(3)",
        "date" => "DATE",
        _ => "STRING",
    }
}

/// Strip characters that break Flink SQL identifier rules.
fn sanitize(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out
        .chars()
        .next()
        .map(|c| c.is_ascii_digit())
        .unwrap_or(false)
    {
        out.insert(0, '_');
    }
    out
}

fn escape_sql(value: &str) -> String {
    value.replace('\'', "''")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::stream::{StreamField, StreamSchema};
    use crate::models::topology::TopologyDefinition;
    use chrono::Utc;
    use uuid::Uuid;

    fn stream(name: &str) -> StreamDefinition {
        StreamDefinition {
            id: Uuid::now_v7(),
            name: name.to_string(),
            description: String::new(),
            status: "active".to_string(),
            schema: StreamSchema {
                fields: vec![
                    StreamField {
                        name: "event_time".to_string(),
                        data_type: "timestamp".to_string(),
                        nullable: false,
                        semantic_role: "event_time".to_string(),
                    },
                    StreamField {
                        name: "customer_id".to_string(),
                        data_type: "string".to_string(),
                        nullable: false,
                        semantic_role: "join_key".to_string(),
                    },
                ],
                primary_key: None,
                watermark_field: Some("event_time".to_string()),
            },
            source_binding: ConnectorBinding {
                connector_type: "kafka".to_string(),
                endpoint: "kafka://stream/orders".to_string(),
                format: "json".to_string(),
                config: serde_json::json!({}),
            },
            retention_hours: 24,
            partitions: 3,
            consistency_guarantee: "at-least-once".to_string(),
            stream_profile: crate::models::stream::StreamProfile::default(),
            schema_avro: None,
            schema_fingerprint: None,
            schema_compatibility_mode: "BACKWARD".to_string(),
            default_marking: None,
            stream_type: crate::models::stream::StreamType::default(),
            compression: false,
            ingest_consistency: crate::models::stream::StreamConsistency::AtLeastOnce,
            pipeline_consistency: crate::models::stream::StreamConsistency::AtLeastOnce,
            checkpoint_interval_ms: 2_000,
            kind: crate::models::stream_view::StreamKind::Ingest,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        }
    }

    fn topology(source: Uuid) -> TopologyDefinition {
        TopologyDefinition {
            id: Uuid::now_v7(),
            name: "demo".to_string(),
            description: String::new(),
            status: "active".to_string(),
            nodes: Vec::new(),
            edges: Vec::new(),
            join_definition: None,
            cep_definition: None,
            backpressure_policy: crate::models::topology::BackpressurePolicy::default(),
            source_stream_ids: vec![source],
            sink_bindings: vec![ConnectorBinding {
                connector_type: "iceberg".to_string(),
                endpoint: "s3://openfoundry-iceberg/sink".to_string(),
                format: "parquet".to_string(),
                config: serde_json::json!({}),
            }],
            state_backend: "rocksdb".to_string(),
            checkpoint_interval_ms: 60_000,
            runtime_kind: "flink".to_string(),
            flink_job_name: Some("demo".into()),
            flink_deployment_name: None,
            flink_job_id: None,
            flink_namespace: None,
            consistency_guarantee: "exactly-once".to_string(),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        }
    }

    #[test]
    fn renders_source_sink_and_insert() {
        let s = stream("orders");
        let topo = topology(s.id);
        let out = render_flink_sql(&topo, &[s]);
        assert!(out.script.contains("CREATE TABLE orders"));
        assert!(out.script.contains("CREATE TABLE sink_0"));
        assert!(out.script.contains("INSERT INTO sink_0"));
        assert!(out.script.contains("EXACTLY_ONCE"));
        assert!(out.script.contains("execution.checkpointing.interval"));
        assert!(out.warnings.is_empty());
    }

    #[test]
    fn warns_when_source_missing_from_catalogue() {
        let topo = topology(Uuid::now_v7());
        let out = render_flink_sql(&topo, &[]);
        assert!(out.warnings.iter().any(|w| w.contains("not found")));
    }

    #[test]
    fn sanitize_replaces_dashes_and_pads_leading_digits() {
        assert_eq!(sanitize("foo-bar"), "foo_bar");
        assert_eq!(sanitize("9lives"), "_9lives");
    }
}
