global:
  existingSecret: open-foundry-dev-env
  podDisruptionBudget:
    enabled: false
  ingress:
    enabled: false
  networkPolicy:
    enabled: false

services:
  gateway:
    replicas: 1
    autoscaling:
      minReplicas: 1
      maxReplicas: 2
      keda:
        enabled: false
  identity-federation-service:
    replicas: 1
    autoscaling:
      minReplicas: 1
      maxReplicas: 2
  data-asset-catalog-service:
    replicas: 1
    autoscaling:
      minReplicas: 1
      maxReplicas: 3
  sql-bi-gateway-service:
    replicas: 1
    env:
      DISTRIBUTED_QUERY_WORKERS: "2"
    autoscaling:
      minReplicas: 1
      maxReplicas: 3
      keda:
        enabled: false
  pipeline-authoring-service:
    replicas: 1
      keda:
        enabled: false
  report-service:
    replicas: 1
    autoscaling:
      minReplicas: 1
      maxReplicas: 2
  nexus-service:
    replicas: 1
    autoscaling:
      minReplicas: 1
      maxReplicas: 2
  geospatial-intelligence-service:
    replicas: 1
    autoscaling:
      minReplicas: 1
      maxReplicas: 2
