global:
  existingSecret: open-foundry-staging-env
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: staging.openfoundry.example.com
        paths:
          - path: /

services:
  gateway:
    autoscaling:
      minReplicas: 2
      maxReplicas: 5
  identity-federation-service:
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
  data-asset-catalog-service:
    autoscaling:
      minReplicas: 2
      maxReplicas: 5
  sql-bi-gateway-service:
    env:
      DISTRIBUTED_QUERY_WORKERS: "4"
    autoscaling:
      minReplicas: 2
      maxReplicas: 8
      keda:
        enabled: true
  pipeline-authoring-service:
    autoscaling:
      minReplicas: 2
      maxReplicas: 6
  report-service:
    autoscaling:
      minReplicas: 2
      maxReplicas: 5
  nexus-service:
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
  geospatial-intelligence-service:
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
