#!/usr/bin/env bash
# S1.9.b - Validate TS/Python SDK clients against the migrated platform.
#
# Variables required:
#   OPENFOUNDRY_BASE_URL   e.g. https://ontology.dev.openfoundry.local
#   OPENFOUNDRY_TOKEN      bearer JWT with read+execute permissions
#   OPENFOUNDRY_TENANT     seeded tenant id
#   OPENFOUNDRY_OBJECT_ID  one object id generated by the S1 bench seed
#   OPENFOUNDRY_TYPE_ID    object type id used by list_by_type
#   OPENFOUNDRY_ACTION_ID  action type id seeded for the write path
#
# Output: smoke/results/sdk-cassandra-parity.json

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RESULTS_DIR="$REPO_ROOT/smoke/results"
OUT="$RESULTS_DIR/sdk-cassandra-parity.json"
mkdir -p "$RESULTS_DIR"

timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
command_used="OPENFOUNDRY_BASE_URL=\$OPENFOUNDRY_BASE_URL OPENFOUNDRY_TOKEN=*** OPENFOUNDRY_TENANT=\$OPENFOUNDRY_TENANT OPENFOUNDRY_OBJECT_ID=\$OPENFOUNDRY_OBJECT_ID OPENFOUNDRY_TYPE_ID=\$OPENFOUNDRY_TYPE_ID OPENFOUNDRY_ACTION_ID=\$OPENFOUNDRY_ACTION_ID smoke/scripts/sdk_cassandra_parity.sh"

write_preflight_fail() {
  local reason="$1"
  local missing_json="$2"

  jq -n \
    --arg timestamp "$timestamp" \
    --arg endpoint "${OPENFOUNDRY_BASE_URL:-}" \
    --arg tenant "${OPENFOUNDRY_TENANT:-}" \
    --arg object "${OPENFOUNDRY_OBJECT_ID:-}" \
    --arg type "${OPENFOUNDRY_TYPE_ID:-}" \
    --arg action "${OPENFOUNDRY_ACTION_ID:-}" \
    --arg command "$command_used" \
    --arg reason "$reason" \
    --argjson missing "$missing_json" \
    '{
      timestamp: $timestamp,
      endpoint: $endpoint,
      tenant: $tenant,
      object: $object,
      type: $type,
      action: $action,
      command: $command,
      status: "fail",
      pass: false,
      checks: [
        {
          client: "harness",
          name: "preflight",
          pass: false,
          reason: $reason,
          missing: $missing
        }
      ],
      clients: {}
    }' > "$OUT"
  echo "wrote $OUT (status=fail)"
}

if ! command -v jq >/dev/null 2>&1; then
  echo "jq no encontrado; no puedo escribir $OUT" >&2
  exit 1
fi

missing_env=()
for name in \
  OPENFOUNDRY_BASE_URL \
  OPENFOUNDRY_TOKEN \
  OPENFOUNDRY_TENANT \
  OPENFOUNDRY_OBJECT_ID \
  OPENFOUNDRY_TYPE_ID \
  OPENFOUNDRY_ACTION_ID; do
  if [[ -z "${!name:-}" ]]; then
    missing_env+=("$name")
  fi
done

if [[ "${#missing_env[@]}" -gt 0 ]]; then
  missing_json="$(printf '%s\n' "${missing_env[@]}" | jq -R . | jq -s .)"
  write_preflight_fail "missing required environment variables" "$missing_json"
  exit 1
fi

missing_bins=()
if ! command -v python3 >/dev/null 2>&1; then
  missing_bins+=("python3")
fi
if ! command -v node >/dev/null 2>&1; then
  missing_bins+=("node")
fi
node_supports_type_strip=false
if command -v node >/dev/null 2>&1 && node --help 2>/dev/null | grep -q -- "strip-types"; then
  node_supports_type_strip=true
fi
if [[ "$node_supports_type_strip" != "true" ]] && ! command -v pnpm >/dev/null 2>&1; then
  missing_bins+=("node-with-typescript-strip-support-or-pnpm")
fi

if [[ "${#missing_bins[@]}" -gt 0 ]]; then
  missing_json="$(printf '%s\n' "${missing_bins[@]}" | jq -R . | jq -s .)"
  write_preflight_fail "missing required commands" "$missing_json"
  exit 1
fi

ts_out="$(mktemp)"
ts_err="$(mktemp)"
py_out="$(mktemp)"
py_err="$(mktemp)"
trap 'rm -f "$ts_out" "$ts_err" "$py_out" "$py_err"' EXIT

# ---- TypeScript SDK -------------------------------------------------
set +e
(
  cd "$REPO_ROOT" || exit 1
  if [[ "$node_supports_type_strip" == "true" ]]; then
    node "$REPO_ROOT/smoke/scripts/sdk_cassandra_parity.ts"
  else
    pnpm dlx tsx "$REPO_ROOT/smoke/scripts/sdk_cassandra_parity.ts"
  fi
) >"$ts_out" 2>"$ts_err"
ts_exit=$?
set -e

# ---- Python SDK -----------------------------------------------------
set +e
(
  cd "$REPO_ROOT/sdks/python/openfoundry-sdk" || exit 1
  if [[ ! -d .venv ]]; then
    python3 -m venv .venv
    ./.venv/bin/pip install -e . >/dev/null
  fi
  ./.venv/bin/python "$REPO_ROOT/smoke/scripts/sdk_cassandra_parity.py"
) >"$py_out" 2>"$py_err"
py_exit=$?
set -e

# ---- Aggregate ------------------------------------------------------
ts_stdout="$(cat "$ts_out")"
ts_stderr="$(cat "$ts_err")"
py_stdout="$(cat "$py_out")"
py_stderr="$(cat "$py_err")"

jq -n \
  --arg timestamp "$timestamp" \
  --arg endpoint "$OPENFOUNDRY_BASE_URL" \
  --arg tenant "$OPENFOUNDRY_TENANT" \
  --arg object "$OPENFOUNDRY_OBJECT_ID" \
  --arg type "$OPENFOUNDRY_TYPE_ID" \
  --arg action "$OPENFOUNDRY_ACTION_ID" \
  --arg command "$command_used" \
  --arg ts_stdout "$ts_stdout" \
  --arg ts_stderr "$ts_stderr" \
  --arg py_stdout "$py_stdout" \
  --arg py_stderr "$py_stderr" \
  --argjson ts_exit "$ts_exit" \
  --argjson py_exit "$py_exit" \
  '
  def parse_client($stdout; $stderr; $exit):
    ($stdout | fromjson? // {
      client: "unknown",
      pass: false,
      checks: [],
      error: "client did not emit valid JSON",
      stdout: $stdout
    }) as $parsed
    | $parsed + {exit: $exit, stderr: $stderr};

  (parse_client($ts_stdout; $ts_stderr; $ts_exit) + {client: "typescript"}) as $ts
  | (parse_client($py_stdout; $py_stderr; $py_exit) + {client: "python"}) as $py
  | (($ts.exit == 0 and $ts.pass == true) and ($py.exit == 0 and $py.pass == true)) as $pass
  | {
      timestamp: $timestamp,
      endpoint: $endpoint,
      tenant: $tenant,
      object: $object,
      type: $type,
      action: $action,
      command: $command,
      status: (if $pass then "pass" else "fail" end),
      pass: $pass,
      checks: (
        (($ts.checks // []) | map(. + {client: "typescript"})) +
        (($py.checks // []) | map(. + {client: "python"}))
      ),
      clients: {
        typescript: $ts,
        python: $py
      }
    }' > "$OUT"

status="$(jq -r '.status' "$OUT")"
echo "wrote $OUT (status=$status)"
[[ "$status" == "pass" ]]
