image:
  registry: registry.registry.svc.cluster.local:5000
  tag: "0.1.0"

global:
  imagePullPolicy: IfNotPresent
  deploymentFabric:
    environment: dev
  autoscaling:
    enabled: false
  resourcesOverride:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi

services:
  edge-gateway-service:
    replicas: 1
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
  identity-federation-service:
    replicas: 1
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
