image:
  registry: registry.registry.svc.cluster.local:5000
  tag: "0.1.0"

global:
  imagePullPolicy: IfNotPresent
  deploymentFabric:
    environment: dev
  autoscaling:
    enabled: false
  resourcesOverride:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi

services:
  edge-gateway-service:
    replicas: 1
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
  identity-federation-service:
    replicas: 1
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
    envSecrets:
      DATABASE_URL:
        secretName: identity-federation-db-dsn
        key: writer_url
      DATABASE_READ_URL:
        secretName: identity-federation-db-dsn
        key: reader_url
  cipher-service:
    envSecrets:
      DATABASE_URL:
        secretName: cipher-db-dsn
        key: writer_url
      DATABASE_READ_URL:
        secretName: cipher-db-dsn
        key: reader_url
  network-boundary-service:
    envSecrets:
      DATABASE_URL:
        secretName: network-boundary-db-dsn
        key: writer_url
      DATABASE_READ_URL:
        secretName: network-boundary-db-dsn
        key: reader_url
  oauth-integration-service:
    envSecrets:
      DATABASE_URL:
        secretName: oauth-integration-db-dsn
        key: writer_url
      DATABASE_READ_URL:
        secretName: oauth-integration-db-dsn
        key: reader_url
  security-governance-service:
    envSecrets:
      DATABASE_URL:
        secretName: security-governance-db-dsn
        key: writer_url
      DATABASE_READ_URL:
        secretName: security-governance-db-dsn
        key: reader_url
  tenancy-organizations-service:
    envSecrets:
      DATABASE_URL:
        secretName: tenancy-organizations-db-dsn
        key: writer_url
      DATABASE_READ_URL:
        secretName: tenancy-organizations-db-dsn
        key: reader_url
