// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: media_set/access_pattern.proto

package media_set

import (
	common "github.com/openfoundry/openfoundry-go/libs/proto-gen/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How derived outputs of an access pattern are stored.
//
// - RECOMPUTE: never persist; re-run the pattern on every request.
// - PERSIST: write the derived artifact alongside the source media item.
// - CACHE_TTL: cache for `ttl_seconds` and recompute after expiry.
type PersistencePolicy int32

const (
	PersistencePolicy_PERSISTENCE_POLICY_UNSPECIFIED PersistencePolicy = 0
	PersistencePolicy_PERSISTENCE_POLICY_RECOMPUTE   PersistencePolicy = 1
	PersistencePolicy_PERSISTENCE_POLICY_PERSIST     PersistencePolicy = 2
	PersistencePolicy_PERSISTENCE_POLICY_CACHE_TTL   PersistencePolicy = 3
)

// Enum value maps for PersistencePolicy.
var (
	PersistencePolicy_name = map[int32]string{
		0: "PERSISTENCE_POLICY_UNSPECIFIED",
		1: "PERSISTENCE_POLICY_RECOMPUTE",
		2: "PERSISTENCE_POLICY_PERSIST",
		3: "PERSISTENCE_POLICY_CACHE_TTL",
	}
	PersistencePolicy_value = map[string]int32{
		"PERSISTENCE_POLICY_UNSPECIFIED": 0,
		"PERSISTENCE_POLICY_RECOMPUTE":   1,
		"PERSISTENCE_POLICY_PERSIST":     2,
		"PERSISTENCE_POLICY_CACHE_TTL":   3,
	}
)

func (x PersistencePolicy) Enum() *PersistencePolicy {
	p := new(PersistencePolicy)
	*p = x
	return p
}

func (x PersistencePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PersistencePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_media_set_access_pattern_proto_enumTypes[0].Descriptor()
}

func (PersistencePolicy) Type() protoreflect.EnumType {
	return &file_media_set_access_pattern_proto_enumTypes[0]
}

func (x PersistencePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PersistencePolicy.Descriptor instead.
func (PersistencePolicy) EnumDescriptor() ([]byte, []int) {
	return file_media_set_access_pattern_proto_rawDescGZIP(), []int{0}
}

// A registered transformation/derivation that can be applied to items in a
// media set (e.g. thumbnail, waveform, OCR, HLS segments, geo tile).
//
// `kind` is a free-form discriminator interpreted by the worker that runs
// the pattern (Pipeline Builder transform, ML model, geo tiler, ...).
// `params` is a JSON blob with kind-specific configuration.
type AccessPattern struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MediaSetRid string                 `protobuf:"bytes,2,opt,name=media_set_rid,json=mediaSetRid,proto3" json:"media_set_rid,omitempty"`
	// Kind of pattern, e.g. `thumbnail`, `waveform`, `ocr`, `hls`, `geo_tile`.
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// Kind-specific configuration as a JSON-encoded string.
	Params      string            `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	Persistence PersistencePolicy `protobuf:"varint,5,opt,name=persistence,proto3,enum=open_foundry.media_set.PersistencePolicy" json:"persistence,omitempty"`
	// TTL in seconds; only consulted when `persistence = CACHE_TTL`.
	TtlSeconds    int64 `protobuf:"varint,6,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessPattern) Reset() {
	*x = AccessPattern{}
	mi := &file_media_set_access_pattern_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessPattern) ProtoMessage() {}

func (x *AccessPattern) ProtoReflect() protoreflect.Message {
	mi := &file_media_set_access_pattern_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessPattern.ProtoReflect.Descriptor instead.
func (*AccessPattern) Descriptor() ([]byte, []int) {
	return file_media_set_access_pattern_proto_rawDescGZIP(), []int{0}
}

func (x *AccessPattern) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessPattern) GetMediaSetRid() string {
	if x != nil {
		return x.MediaSetRid
	}
	return ""
}

func (x *AccessPattern) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AccessPattern) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *AccessPattern) GetPersistence() PersistencePolicy {
	if x != nil {
		return x.Persistence
	}
	return PersistencePolicy_PERSISTENCE_POLICY_UNSPECIFIED
}

func (x *AccessPattern) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type RegisterAccessPatternRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaSetRid   string                 `protobuf:"bytes,1,opt,name=media_set_rid,json=mediaSetRid,proto3" json:"media_set_rid,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Params        string                 `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	Persistence   PersistencePolicy      `protobuf:"varint,4,opt,name=persistence,proto3,enum=open_foundry.media_set.PersistencePolicy" json:"persistence,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAccessPatternRequest) Reset() {
	*x = RegisterAccessPatternRequest{}
	mi := &file_media_set_access_pattern_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccessPatternRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccessPatternRequest) ProtoMessage() {}

func (x *RegisterAccessPatternRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_set_access_pattern_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccessPatternRequest.ProtoReflect.Descriptor instead.
func (*RegisterAccessPatternRequest) Descriptor() ([]byte, []int) {
	return file_media_set_access_pattern_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAccessPatternRequest) GetMediaSetRid() string {
	if x != nil {
		return x.MediaSetRid
	}
	return ""
}

func (x *RegisterAccessPatternRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RegisterAccessPatternRequest) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *RegisterAccessPatternRequest) GetPersistence() PersistencePolicy {
	if x != nil {
		return x.Persistence
	}
	return PersistencePolicy_PERSISTENCE_POLICY_UNSPECIFIED
}

func (x *RegisterAccessPatternRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type ListAccessPatternsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaSetRid   string                 `protobuf:"bytes,1,opt,name=media_set_rid,json=mediaSetRid,proto3" json:"media_set_rid,omitempty"`
	Pagination    *common.PageRequest    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessPatternsRequest) Reset() {
	*x = ListAccessPatternsRequest{}
	mi := &file_media_set_access_pattern_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessPatternsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessPatternsRequest) ProtoMessage() {}

func (x *ListAccessPatternsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_set_access_pattern_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessPatternsRequest.ProtoReflect.Descriptor instead.
func (*ListAccessPatternsRequest) Descriptor() ([]byte, []int) {
	return file_media_set_access_pattern_proto_rawDescGZIP(), []int{2}
}

func (x *ListAccessPatternsRequest) GetMediaSetRid() string {
	if x != nil {
		return x.MediaSetRid
	}
	return ""
}

func (x *ListAccessPatternsRequest) GetPagination() *common.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListAccessPatternsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patterns      []*AccessPattern       `protobuf:"bytes,1,rep,name=patterns,proto3" json:"patterns,omitempty"`
	Pagination    *common.PageResponse   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessPatternsResponse) Reset() {
	*x = ListAccessPatternsResponse{}
	mi := &file_media_set_access_pattern_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessPatternsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessPatternsResponse) ProtoMessage() {}

func (x *ListAccessPatternsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_set_access_pattern_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessPatternsResponse.ProtoReflect.Descriptor instead.
func (*ListAccessPatternsResponse) Descriptor() ([]byte, []int) {
	return file_media_set_access_pattern_proto_rawDescGZIP(), []int{3}
}

func (x *ListAccessPatternsResponse) GetPatterns() []*AccessPattern {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *ListAccessPatternsResponse) GetPagination() *common.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type RunAccessPatternRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessPatternId string                 `protobuf:"bytes,1,opt,name=access_pattern_id,json=accessPatternId,proto3" json:"access_pattern_id,omitempty"`
	// Item to apply the pattern to.
	MediaItemRid string `protobuf:"bytes,2,opt,name=media_item_rid,json=mediaItemRid,proto3" json:"media_item_rid,omitempty"`
	// Optional override of the registered params, JSON-encoded.
	ParamsOverride string `protobuf:"bytes,3,opt,name=params_override,json=paramsOverride,proto3" json:"params_override,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunAccessPatternRequest) Reset() {
	*x = RunAccessPatternRequest{}
	mi := &file_media_set_access_pattern_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAccessPatternRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAccessPatternRequest) ProtoMessage() {}

func (x *RunAccessPatternRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_set_access_pattern_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAccessPatternRequest.ProtoReflect.Descriptor instead.
func (*RunAccessPatternRequest) Descriptor() ([]byte, []int) {
	return file_media_set_access_pattern_proto_rawDescGZIP(), []int{4}
}

func (x *RunAccessPatternRequest) GetAccessPatternId() string {
	if x != nil {
		return x.AccessPatternId
	}
	return ""
}

func (x *RunAccessPatternRequest) GetMediaItemRid() string {
	if x != nil {
		return x.MediaItemRid
	}
	return ""
}

func (x *RunAccessPatternRequest) GetParamsOverride() string {
	if x != nil {
		return x.ParamsOverride
	}
	return ""
}

type RunAccessPatternResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Presigned URL pointing to the computed/cached artifact.
	ResultUrl string `protobuf:"bytes,1,opt,name=result_url,json=resultUrl,proto3" json:"result_url,omitempty"`
	MimeType  string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes int64  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// True if the result was served from cache or persisted storage.
	Cached        bool `protobuf:"varint,4,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAccessPatternResponse) Reset() {
	*x = RunAccessPatternResponse{}
	mi := &file_media_set_access_pattern_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAccessPatternResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAccessPatternResponse) ProtoMessage() {}

func (x *RunAccessPatternResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_set_access_pattern_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAccessPatternResponse.ProtoReflect.Descriptor instead.
func (*RunAccessPatternResponse) Descriptor() ([]byte, []int) {
	return file_media_set_access_pattern_proto_rawDescGZIP(), []int{5}
}

func (x *RunAccessPatternResponse) GetResultUrl() string {
	if x != nil {
		return x.ResultUrl
	}
	return ""
}

func (x *RunAccessPatternResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *RunAccessPatternResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *RunAccessPatternResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

var File_media_set_access_pattern_proto protoreflect.FileDescriptor

const file_media_set_access_pattern_proto_rawDesc = "" +
	"\n" +
	"\x1emedia_set/access_pattern.proto\x12\x16open_foundry.media_set\x1a\x12common/types.proto\"\xdd\x01\n" +
	"\rAccessPattern\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\rmedia_set_rid\x18\x02 \x01(\tR\vmediaSetRid\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06params\x18\x04 \x01(\tR\x06params\x12K\n" +
	"\vpersistence\x18\x05 \x01(\x0e2).open_foundry.media_set.PersistencePolicyR\vpersistence\x12\x1f\n" +
	"\vttl_seconds\x18\x06 \x01(\x03R\n" +
	"ttlSeconds\"\xdc\x01\n" +
	"\x1cRegisterAccessPatternRequest\x12\"\n" +
	"\rmedia_set_rid\x18\x01 \x01(\tR\vmediaSetRid\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06params\x18\x03 \x01(\tR\x06params\x12K\n" +
	"\vpersistence\x18\x04 \x01(\x0e2).open_foundry.media_set.PersistencePolicyR\vpersistence\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x03R\n" +
	"ttlSeconds\"\x81\x01\n" +
	"\x19ListAccessPatternsRequest\x12\"\n" +
	"\rmedia_set_rid\x18\x01 \x01(\tR\vmediaSetRid\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .open_foundry.common.PageRequestR\n" +
	"pagination\"\xa2\x01\n" +
	"\x1aListAccessPatternsResponse\x12A\n" +
	"\bpatterns\x18\x01 \x03(\v2%.open_foundry.media_set.AccessPatternR\bpatterns\x12A\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2!.open_foundry.common.PageResponseR\n" +
	"pagination\"\x94\x01\n" +
	"\x17RunAccessPatternRequest\x12*\n" +
	"\x11access_pattern_id\x18\x01 \x01(\tR\x0faccessPatternId\x12$\n" +
	"\x0emedia_item_rid\x18\x02 \x01(\tR\fmediaItemRid\x12'\n" +
	"\x0fparams_override\x18\x03 \x01(\tR\x0eparamsOverride\"\x8d\x01\n" +
	"\x18RunAccessPatternResponse\x12\x1d\n" +
	"\n" +
	"result_url\x18\x01 \x01(\tR\tresultUrl\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06cached\x18\x04 \x01(\bR\x06cached*\x9b\x01\n" +
	"\x11PersistencePolicy\x12\"\n" +
	"\x1ePERSISTENCE_POLICY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPERSISTENCE_POLICY_RECOMPUTE\x10\x01\x12\x1e\n" +
	"\x1aPERSISTENCE_POLICY_PERSIST\x10\x02\x12 \n" +
	"\x1cPERSISTENCE_POLICY_CACHE_TTL\x10\x032\x80\x03\n" +
	"\x14AccessPatternService\x12t\n" +
	"\x15RegisterAccessPattern\x124.open_foundry.media_set.RegisterAccessPatternRequest\x1a%.open_foundry.media_set.AccessPattern\x12{\n" +
	"\x12ListAccessPatterns\x121.open_foundry.media_set.ListAccessPatternsRequest\x1a2.open_foundry.media_set.ListAccessPatternsResponse\x12u\n" +
	"\x10RunAccessPattern\x12/.open_foundry.media_set.RunAccessPatternRequest\x1a0.open_foundry.media_set.RunAccessPatternResponseb\x06proto3"

var (
	file_media_set_access_pattern_proto_rawDescOnce sync.Once
	file_media_set_access_pattern_proto_rawDescData []byte
)

func file_media_set_access_pattern_proto_rawDescGZIP() []byte {
	file_media_set_access_pattern_proto_rawDescOnce.Do(func() {
		file_media_set_access_pattern_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_set_access_pattern_proto_rawDesc), len(file_media_set_access_pattern_proto_rawDesc)))
	})
	return file_media_set_access_pattern_proto_rawDescData
}

var file_media_set_access_pattern_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_media_set_access_pattern_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_media_set_access_pattern_proto_goTypes = []any{
	(PersistencePolicy)(0),               // 0: open_foundry.media_set.PersistencePolicy
	(*AccessPattern)(nil),                // 1: open_foundry.media_set.AccessPattern
	(*RegisterAccessPatternRequest)(nil), // 2: open_foundry.media_set.RegisterAccessPatternRequest
	(*ListAccessPatternsRequest)(nil),    // 3: open_foundry.media_set.ListAccessPatternsRequest
	(*ListAccessPatternsResponse)(nil),   // 4: open_foundry.media_set.ListAccessPatternsResponse
	(*RunAccessPatternRequest)(nil),      // 5: open_foundry.media_set.RunAccessPatternRequest
	(*RunAccessPatternResponse)(nil),     // 6: open_foundry.media_set.RunAccessPatternResponse
	(*common.PageRequest)(nil),           // 7: open_foundry.common.PageRequest
	(*common.PageResponse)(nil),          // 8: open_foundry.common.PageResponse
}
var file_media_set_access_pattern_proto_depIdxs = []int32{
	0, // 0: open_foundry.media_set.AccessPattern.persistence:type_name -> open_foundry.media_set.PersistencePolicy
	0, // 1: open_foundry.media_set.RegisterAccessPatternRequest.persistence:type_name -> open_foundry.media_set.PersistencePolicy
	7, // 2: open_foundry.media_set.ListAccessPatternsRequest.pagination:type_name -> open_foundry.common.PageRequest
	1, // 3: open_foundry.media_set.ListAccessPatternsResponse.patterns:type_name -> open_foundry.media_set.AccessPattern
	8, // 4: open_foundry.media_set.ListAccessPatternsResponse.pagination:type_name -> open_foundry.common.PageResponse
	2, // 5: open_foundry.media_set.AccessPatternService.RegisterAccessPattern:input_type -> open_foundry.media_set.RegisterAccessPatternRequest
	3, // 6: open_foundry.media_set.AccessPatternService.ListAccessPatterns:input_type -> open_foundry.media_set.ListAccessPatternsRequest
	5, // 7: open_foundry.media_set.AccessPatternService.RunAccessPattern:input_type -> open_foundry.media_set.RunAccessPatternRequest
	1, // 8: open_foundry.media_set.AccessPatternService.RegisterAccessPattern:output_type -> open_foundry.media_set.AccessPattern
	4, // 9: open_foundry.media_set.AccessPatternService.ListAccessPatterns:output_type -> open_foundry.media_set.ListAccessPatternsResponse
	6, // 10: open_foundry.media_set.AccessPatternService.RunAccessPattern:output_type -> open_foundry.media_set.RunAccessPatternResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_media_set_access_pattern_proto_init() }
func file_media_set_access_pattern_proto_init() {
	if File_media_set_access_pattern_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_set_access_pattern_proto_rawDesc), len(file_media_set_access_pattern_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_set_access_pattern_proto_goTypes,
		DependencyIndexes: file_media_set_access_pattern_proto_depIdxs,
		EnumInfos:         file_media_set_access_pattern_proto_enumTypes,
		MessageInfos:      file_media_set_access_pattern_proto_msgTypes,
	}.Build()
	File_media_set_access_pattern_proto = out.File
	file_media_set_access_pattern_proto_goTypes = nil
	file_media_set_access_pattern_proto_depIdxs = nil
}
