package flink

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/google/uuid"

	"github.com/openfoundry/openfoundry-go/services/ingestion-replication-service/internal/domain"
)

// RenderedFlinkSQL mirrors event_streaming::runtime::flink::sql::RenderedFlinkSql.
type RenderedFlinkSQL struct {
	Script   string
	Warnings []string
}

// RenderFlinkSQL ports event_streaming::runtime::flink::sql::render_flink_sql.
//
// Translates a TopologyDefinition + the source streams it references
// into a self-contained Flink SQL script the `sql-runner.jar` job can
// execute end-to-end. Sinks come from topology.SinkBindings.
//
// The renderer is deliberately pragmatic — it covers the topology shapes
// the in-process engine already understands (source / filter / map /
// window / join / sink) and emits warnings for anything fancier so the
// operator can hand-edit. Producing executable SQL for every shape is
// out of scope for the MVP.
func RenderFlinkSQL(topology *domain.TopologyDefinition, streams []domain.DomainStreamDefinition) RenderedFlinkSQL {
	var script strings.Builder
	var warnings []string

	// -- Header ---------------------------------------------------------
	fmt.Fprintln(&script, "-- Auto-generated by ingestion-replication-service / runtime/flink/sql.go")
	fmt.Fprintf(&script, "-- topology: %s (%s)\n", topology.Name, topology.ID)
	exactlyOnce := EffectiveExactlyOnce(topology, streams)
	mode := "AT_LEAST_ONCE"
	if exactlyOnce {
		mode = "EXACTLY_ONCE"
	}
	fmt.Fprintf(&script, "SET 'execution.checkpointing.mode' = '%s';\n", mode)
	fmt.Fprintf(&script, "SET 'execution.checkpointing.interval' = '%d';\n", topology.CheckpointIntervalMS)
	if exactlyOnce {
		// Transactional Kafka sink + two-phase commit. Disabled when
		// AT_LEAST_ONCE so the cheaper write path stays the default.
		fmt.Fprintf(&script, "SET 'sink.transactional-id-prefix' = 'openfoundry-%s';\n", uuidSimple(topology.ID))
		fmt.Fprintln(&script, "SET 'sink.delivery-guarantee' = 'exactly-once';")
	}
	fmt.Fprintln(&script)

	// -- Source tables --------------------------------------------------
	for _, streamID := range topology.SourceStreamIDs {
		stream := findStreamByID(streams, streamID)
		if stream == nil {
			warnings = append(warnings, fmt.Sprintf("source stream %s referenced but not found in catalogue", streamID))
			continue
		}
		renderSourceTable(&script, stream)
		fmt.Fprintln(&script)
	}

	// -- Sink tables ----------------------------------------------------
	for idx, sink := range topology.SinkBindings {
		renderSinkTable(&script, idx, sink)
		fmt.Fprintln(&script)
	}

	// -- Pipeline body --------------------------------------------------
	if join := topology.JoinDefinition; join != nil {
		left := streamNameOrFallback(streams, join.LeftStreamID)
		right := streamNameOrFallback(streams, join.RightStreamID)
		var on string
		if len(join.KeyFields) == 0 {
			on = "1 = 1"
		} else {
			parts := make([]string, len(join.KeyFields))
			for i, k := range join.KeyFields {
				k := sanitize(k)
				parts[i] = fmt.Sprintf("l.%s = r.%s", k, k)
			}
			on = strings.Join(parts, " AND ")
		}
		fmt.Fprintf(&script, "-- Join '%s' over a %d s interval window\n", join.TableName, join.WindowSeconds)
		fmt.Fprintf(&script, "CREATE VIEW %s AS\n", sanitize(join.TableName))
		fmt.Fprintf(
			&script,
			"  SELECT l.*, r.* FROM %s l\n    %s JOIN %s r\n    ON %s\n    AND r.event_time BETWEEN l.event_time - INTERVAL '%d' SECOND\n                         AND l.event_time + INTERVAL '%d' SECOND;\n",
			left,
			joinKindKeyword(join.JoinType),
			right,
			on,
			join.WindowSeconds,
			join.WindowSeconds,
		)
		fmt.Fprintln(&script)
	}

	if topology.CepDefinition != nil {
		warnings = append(warnings, "CEP pattern translation is unsupported by the current Flink SQL renderer")
		fmt.Fprintln(&script, "-- CEP definition is not translated by this renderer; use a supported graph shape")
		fmt.Fprintln(&script)
	}

	// -- Final INSERT INTO sinks ---------------------------------------
	switch {
	case len(topology.SinkBindings) == 0:
		warnings = append(warnings, "topology has no sink bindings; no INSERT INTO emitted")
	case len(topology.SourceStreamIDs) == 0:
		warnings = append(warnings, "topology has no source streams; emitting empty INSERT INTO")
	default:
		primarySource := topology.SourceStreamIDs[0]
		sourceName := streamNameOrFallback(streams, primarySource)
		// Optional WHERE clause aggregated from filter nodes — same
		// shape across every sink, like the Rust source.
		var wheres []string
		for _, node := range topology.Nodes {
			if node.NodeType != "filter" {
				continue
			}
			if expr, ok := readStringFromConfig(node.Config, "expression"); ok {
				wheres = append(wheres, expr)
			}
		}
		whereClause := ""
		if len(wheres) > 0 {
			whereClause = "\n  WHERE " + strings.Join(wheres, " AND ")
		}
		for idx := range topology.SinkBindings {
			fmt.Fprintf(&script, "INSERT INTO sink_%d\n  SELECT * FROM %s%s;\n", idx, sourceName, whereClause)
			fmt.Fprintln(&script)
		}
	}

	return RenderedFlinkSQL{Script: script.String(), Warnings: warnings}
}

func renderSourceTable(out *strings.Builder, stream *domain.DomainStreamDefinition) {
	table := sanitize(stream.Name)
	fmt.Fprintf(out, "CREATE TABLE %s (\n", table)
	n := len(stream.Schema.Fields)
	for i, field := range stream.Schema.Fields {
		comma := ","
		if i+1 == n {
			comma = ""
		}
		nullable := " NOT NULL"
		if field.Nullable {
			nullable = ""
		}
		fmt.Fprintf(out, "  %s %s%s%s\n", sanitize(field.Name), mapType(field.DataType), nullable, comma)
	}
	if wm := stream.Schema.WatermarkField; wm != nil {
		w := sanitize(*wm)
		fmt.Fprintf(out, "  ,WATERMARK FOR %s AS %s - INTERVAL '5' SECOND\n", w, w)
	}
	fmt.Fprintln(out, ") WITH (")
	with := withClauseFor(stream.SourceBinding)
	m := len(with)
	for i, kv := range with {
		comma := ","
		if i+1 == m {
			comma = ""
		}
		fmt.Fprintf(out, "  '%s' = '%s'%s\n", kv.Key, escapeSQL(kv.Value), comma)
	}
	fmt.Fprintln(out, ");")
}

func renderSinkTable(out *strings.Builder, idx int, binding domain.ConnectorBinding) {
	fmt.Fprintf(out, "-- sink #%d (%s → %s)\n", idx, binding.ConnectorType, binding.Endpoint)
	fmt.Fprintf(out, "CREATE TABLE sink_%d (\n", idx)
	fmt.Fprintln(out, "  payload STRING")
	fmt.Fprintln(out, ") WITH (")
	with := withClauseFor(binding)
	m := len(with)
	for i, kv := range with {
		comma := ","
		if i+1 == m {
			comma = ""
		}
		fmt.Fprintf(out, "  '%s' = '%s'%s\n", kv.Key, escapeSQL(kv.Value), comma)
	}
	fmt.Fprintln(out, ");")
}

type kvPair struct{ Key, Value string }

func withClauseFor(binding domain.ConnectorBinding) []kvPair {
	switch binding.ConnectorType {
	case "kafka", "":
		topic := strings.TrimPrefix(binding.Endpoint, "kafka://")
		return []kvPair{
			{"connector", "kafka"},
			{"topic", topic},
			{"properties.bootstrap.servers", envOr("KAFKA_BOOTSTRAP_SERVERS", "kafka:9092")},
			{"format", binding.Format},
			{"scan.startup.mode", "earliest-offset"},
		}
	case "iceberg":
		return []kvPair{
			{"connector", "iceberg"},
			{"catalog-name", "openfoundry"},
			{"warehouse", binding.Endpoint},
		}
	case "filesystem":
		return []kvPair{
			{"connector", "filesystem"},
			{"path", binding.Endpoint},
			{"format", binding.Format},
		}
	default:
		return []kvPair{
			{"connector", binding.ConnectorType},
			{"path", binding.Endpoint},
		}
	}
}

func mapType(t string) string {
	switch strings.ToLower(t) {
	case "string", "text", "varchar":
		return "STRING"
	case "int", "integer", "int32":
		return "INT"
	case "long", "bigint", "int64":
		return "BIGINT"
	case "double", "float64":
		return "DOUBLE"
	case "float", "float32":
		return "FLOAT"
	case "boolean", "bool":
		return "BOOLEAN"
	case "timestamp":
		return "TIMESTAMP(3)"
	case "date":
		return "DATE"
	default:
		return "STRING"
	}
}

// sanitize strips characters that break Flink SQL identifier rules and
// pads a leading digit so the result is a valid identifier.
func sanitize(name string) string {
	var b strings.Builder
	b.Grow(len(name))
	for _, ch := range name {
		switch {
		case ch >= 'a' && ch <= 'z',
			ch >= 'A' && ch <= 'Z',
			ch >= '0' && ch <= '9',
			ch == '_':
			b.WriteRune(ch)
		default:
			b.WriteByte('_')
		}
	}
	out := b.String()
	if len(out) > 0 && out[0] >= '0' && out[0] <= '9' {
		return "_" + out
	}
	return out
}

func escapeSQL(value string) string {
	return strings.ReplaceAll(value, "'", "''")
}

func joinKindKeyword(joinType string) string {
	switch joinType {
	case "left":
		return "LEFT"
	case "right":
		return "RIGHT"
	case "full":
		return "FULL"
	default:
		return "INNER"
	}
}

func uuidSimple(id uuid.UUID) string {
	return strings.ReplaceAll(id.String(), "-", "")
}

func findStreamByID(streams []domain.DomainStreamDefinition, id uuid.UUID) *domain.DomainStreamDefinition {
	for i := range streams {
		if streams[i].ID == id {
			return &streams[i]
		}
	}
	return nil
}

func streamNameOrFallback(streams []domain.DomainStreamDefinition, id uuid.UUID) string {
	if s := findStreamByID(streams, id); s != nil {
		return sanitize(s.Name)
	}
	return "src_" + uuidSimple(id)
}

func containsUUID(haystack []uuid.UUID, needle uuid.UUID) bool {
	for _, id := range haystack {
		if id == needle {
			return true
		}
	}
	return false
}

func readStringFromConfig(raw json.RawMessage, key string) (string, bool) {
	if len(raw) == 0 {
		return "", false
	}
	var obj map[string]any
	if err := json.Unmarshal(raw, &obj); err != nil {
		return "", false
	}
	v, ok := obj[key]
	if !ok {
		return "", false
	}
	s, ok := v.(string)
	return s, ok
}
