use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, Deserialize, Default)]
pub struct HyperAutoErpRequest {
    #[serde(default)]
    pub selectors: Vec<String>,
    pub max_entities: Option<usize>,
    pub sample_limit: Option<usize>,
    pub schedule_cron: Option<String>,
    pub pipeline_status: Option<String>,
    pub queue_initial_sync: Option<bool>,
    pub create_link_types: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HyperAutoErpFieldPlan {
    pub source_name: String,
    pub property_name: String,
    pub property_type: String,
    pub nullable: bool,
    pub unique_constraint: bool,
    pub semantic_role: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HyperAutoErpEntityPlan {
    pub selector: String,
    pub display_name: String,
    pub source_kind: String,
    pub module: String,
    pub sample_row_count: usize,
    pub raw_dataset_name: String,
    pub curated_dataset_name: String,
    pub pipeline_name: String,
    pub object_type_name: String,
    pub object_display_name: String,
    pub primary_key_property: Option<String>,
    pub normalization_sql: String,
    pub fields: Vec<HyperAutoErpFieldPlan>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HyperAutoErpLinkPlan {
    pub name: String,
    pub display_name: String,
    pub source_object_type_name: String,
    pub target_object_type_name: String,
    pub source_property_name: String,
    pub target_primary_key_property: Option<String>,
    pub cardinality: String,
    pub rationale: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HyperAutoErpPreviewResponse {
    pub connection_id: Uuid,
    pub connection_name: String,
    pub connector_type: String,
    pub erp_system: String,
    pub generated_at: DateTime<Utc>,
    pub entity_count: usize,
    pub pipeline_status: String,
    pub schedule_cron: Option<String>,
    pub entities: Vec<HyperAutoErpEntityPlan>,
    pub links: Vec<HyperAutoErpLinkPlan>,
    pub warnings: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HyperAutoGeneratedDataset {
    pub selector: String,
    pub dataset_id: Uuid,
    pub dataset_name: String,
    pub stage: String,
    pub reused: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HyperAutoGeneratedRegistration {
    pub selector: String,
    pub registration_id: Uuid,
    pub target_dataset_id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HyperAutoGeneratedPipeline {
    pub selector: String,
    pub pipeline_id: Uuid,
    pub pipeline_name: String,
    pub reused: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HyperAutoGeneratedObjectType {
    pub selector: String,
    pub object_type_id: Uuid,
    pub object_type_name: String,
    pub reused: bool,
    pub properties_created: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HyperAutoGeneratedLinkType {
    pub name: String,
    pub link_type_id: Uuid,
    pub reused: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HyperAutoQueuedSyncJob {
    pub selector: String,
    pub job_id: Uuid,
    pub target_dataset_id: Uuid,
    pub scheduled_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HyperAutoErpGenerateResponse {
    pub preview: HyperAutoErpPreviewResponse,
    pub raw_datasets: Vec<HyperAutoGeneratedDataset>,
    pub curated_datasets: Vec<HyperAutoGeneratedDataset>,
    pub registrations: Vec<HyperAutoGeneratedRegistration>,
    pub pipelines: Vec<HyperAutoGeneratedPipeline>,
    pub object_types: Vec<HyperAutoGeneratedObjectType>,
    pub link_types: Vec<HyperAutoGeneratedLinkType>,
    pub sync_jobs: Vec<HyperAutoQueuedSyncJob>,
}
