services:
  sql-bi-gateway-service:
    replicas: 1
    env:
      DISTRIBUTED_QUERY_WORKERS: "2"
      RUST_LOG: info
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
      keda:
        enabled: false
  pipeline-build-service:
    replicas: 1
