// Package notepad ports services/notebook-runtime-service/src/domain/notepad.rs
// 1:1: HTML rendering for notepad documents (export endpoint), the
// stale-presence cleanup SQL, and the markdown→HTML mini-renderer.
package notepad

import (
	"encoding/json"
	"strings"

	"github.com/openfoundry/openfoundry-go/services/notebook-runtime-service/internal/models"
)

// CleanupStalePresenceSQL returns the DELETE statement applied before
// every presence list/upsert. Mirrors the Rust constant verbatim so
// the same Postgres plan is used regardless of which language served
// the request.
func CleanupStalePresenceSQL() string {
	return "DELETE FROM notepad_presence WHERE last_seen_at < NOW() - INTERVAL '5 minutes'"
}

// RenderExportPayload builds the export envelope returned by the
// `/notepad/{id}/export` endpoint.
func RenderExportPayload(doc *models.NotepadDocument) models.NotepadExportPayload {
	title := strings.TrimSpace(doc.Title)
	html := RenderDocumentHTML(doc)
	previewExcerpt := previewExcerpt(doc.Content)

	return models.NotepadExportPayload{
		FileName:       slugify(title) + ".html",
		MimeType:       "text/html",
		Title:          title,
		HTML:           html,
		PreviewExcerpt: previewExcerpt,
	}
}

// RenderDocumentHTML produces the standalone HTML page Foundry-style.
// The CSS payload is embedded so the export is portable.
func RenderDocumentHTML(doc *models.NotepadDocument) string {
	title := escapeHTML(strings.TrimSpace(doc.Title))
	descriptionTrimmed := strings.TrimSpace(doc.Description)
	var descriptionHTML string
	if descriptionTrimmed != "" {
		descriptionHTML = `<p class="lede">` + escapeHTML(descriptionTrimmed) + `</p>`
	}

	return `<!doctype html><html><head><meta charset="utf-8" />` +
		`<meta name="viewport" content="width=device-width, initial-scale=1" />` +
		`<title>` + title + `</title>` +
		`<style>` + baseStyles() + `</style></head>` +
		`<body><article class="document"><header>` +
		`<div class="eyebrow">Notepad</div><h1>` + title + `</h1>` +
		descriptionHTML +
		`</header><section class="content">` + RenderMarkdown(doc.Content) + `</section>` +
		renderWidgets(doc.Widgets) +
		`<footer>Generated by OpenFoundry Notepad</footer></article></body></html>`
}

// RenderMarkdown is the same minimal markdown subset the Rust impl
// understands: H1/H2/H3, bullet lists (`- `), and paragraph fallthrough.
// Anything else falls through as a paragraph.
func RenderMarkdown(md string) string {
	var b strings.Builder
	inList := false
	for _, raw := range strings.Split(md, "\n") {
		line := strings.TrimRight(raw, " \t")
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			if inList {
				b.WriteString("</ul>")
				inList = false
			}
			continue
		}
		switch {
		case strings.HasPrefix(trimmed, "### "):
			if inList {
				b.WriteString("</ul>")
				inList = false
			}
			b.WriteString("<h3>" + escapeHTML(trimmed[4:]) + "</h3>")
		case strings.HasPrefix(trimmed, "## "):
			if inList {
				b.WriteString("</ul>")
				inList = false
			}
			b.WriteString("<h2>" + escapeHTML(trimmed[3:]) + "</h2>")
		case strings.HasPrefix(trimmed, "# "):
			if inList {
				b.WriteString("</ul>")
				inList = false
			}
			b.WriteString("<h1>" + escapeHTML(trimmed[2:]) + "</h1>")
		case strings.HasPrefix(trimmed, "- "):
			if !inList {
				b.WriteString("<ul>")
				inList = true
			}
			b.WriteString("<li>" + escapeHTML(trimmed[2:]) + "</li>")
		default:
			if inList {
				b.WriteString("</ul>")
				inList = false
			}
			b.WriteString("<p>" + escapeHTML(trimmed) + "</p>")
		}
	}
	if inList {
		b.WriteString("</ul>")
	}
	return b.String()
}

func renderWidgets(widgets json.RawMessage) string {
	if len(widgets) == 0 {
		return ""
	}
	var entries []map[string]any
	if err := json.Unmarshal(widgets, &entries); err != nil || len(entries) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString(`<section class="widgets"><div class="section-label">Embedded widgets</div>`)
	b.WriteString(`<div class="widget-grid">`)
	for _, w := range entries {
		title := stringField(w, "title", "Embedded widget")
		kind := stringField(w, "kind", "widget")
		summary := stringField(w, "summary", "Live content rendered in the OpenFoundry workspace.")
		b.WriteString(`<div class="widget-card"><div class="widget-kind">`)
		b.WriteString(escapeHTML(kind))
		b.WriteString(`</div><h3>`)
		b.WriteString(escapeHTML(title))
		b.WriteString(`</h3><p>`)
		b.WriteString(escapeHTML(summary))
		b.WriteString(`</p></div>`)
	}
	b.WriteString(`</div></section>`)
	return b.String()
}

func stringField(m map[string]any, key, fallback string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return fallback
}

// previewExcerpt grabs the first non-empty line, trimmed, capped at
// 180 chars — same heuristic as the Rust impl.
func previewExcerpt(content string) string {
	for _, line := range strings.Split(content, "\n") {
		t := strings.TrimSpace(line)
		if t == "" {
			continue
		}
		runes := []rune(t)
		if len(runes) > 180 {
			return string(runes[:180])
		}
		return t
	}
	return "Document export"
}

func slugify(value string) string {
	var b strings.Builder
	for _, c := range value {
		switch {
		case c >= 'a' && c <= 'z':
			b.WriteRune(c)
		case c >= 'A' && c <= 'Z':
			b.WriteRune(c + ('a' - 'A'))
		case c >= '0' && c <= '9':
			b.WriteRune(c)
		default:
			b.WriteRune('-')
		}
	}
	return strings.Trim(b.String(), "-")
}

func escapeHTML(s string) string {
	r := strings.NewReplacer(
		"&", "&amp;",
		"<", "&lt;",
		">", "&gt;",
		`"`, "&quot;",
		"'", "&#39;",
	)
	return r.Replace(s)
}

func baseStyles() string {
	return `body{margin:0;background:#f8fafc;color:#0f172a;font:16px/1.65 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;} .document{max-width:900px;margin:0 auto;padding:56px 28px 96px;} .eyebrow{font-size:12px;letter-spacing:.24em;text-transform:uppercase;color:#0f766e;font-weight:700;} h1,h2,h3{line-height:1.15;color:#020617;} h1{font-size:44px;margin:12px 0 16px;} h2{font-size:28px;margin:32px 0 12px;} h3{font-size:20px;margin:24px 0 8px;} p,li{color:#334155;} .lede{font-size:18px;color:#475569;margin-bottom:24px;} ul{padding-left:22px;} .widgets{margin-top:40px;} .section-label{font-size:12px;letter-spacing:.2em;text-transform:uppercase;color:#475569;font-weight:700;margin-bottom:12px;} .widget-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px;} .widget-card{border:1px solid #cbd5e1;border-radius:18px;padding:18px;background:white;box-shadow:0 10px 30px rgba(15,23,42,.06);} .widget-kind{font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#0284c7;font-weight:700;margin-bottom:8px;} footer{margin-top:48px;padding-top:20px;border-top:1px solid #e2e8f0;color:#64748b;font-size:13px;}`
}
